project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Ben Stanley"

  page-footer:
    left: ""
    right: ""

  navbar:
    left:
      - href: index.qmd
        text: Home
        
      - href: publications.qmd
        text: Publications

      - href: research projects.qmd
        text: Research projects
        
      - href: media.qmd
        text: Media
      
      - href: Pooling the Poles.qmd
        text: Pooling the Poles
        
    right:
      - href: cv.qmd
        text: CV
    
      - text: "{{< fa brands whatsapp >}}"
        href: "tel:+48798814801"
        
      - text: "{{< iconify bi envelope size=1.1em title='E-mail' >}}"
        href: mailto:bstanley@swps.edu.pl
        
      - text: "{{< iconify fa6-brands bluesky size=1.1em title='Bluesky' >}}"
        href: https://bsky.app/profile/benstanley.pl
        
      - text: "{{< ai orcid >}}"
        href: https://orcid.org/my-orcid?orcid=0000-0001-6932-1046
        
      - text: "{{< ai google-scholar >}}"
        href: https://scholar.google.com/citations?user=8AO7H9gAAAAJ&hl=en
        
      - text: "{{< ai clarivate >}}"
        href: https://www.webofscience.com/wos/author/record/J-7051-2013
        
      - text: "{{< iconify bi github size=1.1em title='GitHub' >}}"
        href: https://github.com/BDStanley
        
      - text: "{{< ai dataverse >}}"
        href: https://dataverse.harvard.edu/dataverse/bdstanley
        
      - text: "{{< ai zotero >}}"
        href: https://www.zotero.org/benstanleypl/library

format:
  html:
    theme:
      - bds.scss
    css: styles.css
    toc: true



