---
editor: visual
---

# Ben Stanley

Associate Professor of Political Science \
SWPS University\
ul. Chodakowska 19/31\
03-815 Warsaw\
Poland\

<center>

**Gender:** Male         **Date of birth:** 17.05.1979        **Nationality:** British, Irish         **Residence:** Poland\

**Phone:** <a href="tel:+48798814801">(+48)798814801</a>          **Email:** <a href="mailto:bstanley@swps.edu.pl">bstanley\@swps.edu.pl</a>           **Website:** <a href="https://www.benstanley.eu">benstanley.eu</a>\

**ORCID:** <a href="https://orcid.org/0000-0001-6932-1046">0000-0001-6932-1046</a>

</center>

## Employment

`2018-present` **Associate Professor**, *Centre for the Study of Democracy, SWPS University*, Warsaw, Poland.

`2015-2018` **Assistant Professor**, *Centre for the Study of Democracy, SWPS University*, Warsaw, Poland.

`2013-2015` **Marie Curie Intra-European Research Fellow**, *School of Law, Politics and Sociology, University of Sussex*, Brighton, United Kingdom.

`2013-2015` **Assistant Professor**, *Faculty of History and Social Sciences, Cardinal Stefan Wyszyński University*, Warsaw, Poland.

`2011` **Guest Researcher**, *Centre for Baltic and East European Studies, Södertörn University*, Stockholm, Sweden.

`2010` **Marie Curie Post-Doctoral Fellow**, *Institute for Public Affairs*, Bratislava, Slovakia.

`2008` **Graduate Teaching Assistant**, *Department of Government, The University of Essex*, Colchester, United Kingdom.

## Qualifications

`2018` **Habilitation, Social Sciences**, *Polish Academy of Sciences*, Warsaw, Poland. Cycle of papers: [*Populism as a normal feature of post-communist politics*.](https://ludzie.nauka.gov.pl/ln/profiles/zxjk14IR1Uy/edit/research-work/fd422ed5-e7ca-4cf4-bea0-839e6911fa68)

`2010` **Ph.D, Government**, *The University of Essex*, Essex, United Kingdom. Dissertation: [*Populism in the Polish party system: party appeals and voter mobilisation*.](https://essex.primo.exlibrisgroup.com/permalink/44UOES_INST/ngp9lg/alma991005529219707346)

`2005` **M.A., European Politics (distinction)**, *The University of Essex*, Essex, United Kingdom. Thesis: *The controversial concept of populism*.

`2001` **M.A., International Studies (distinction)**, *The University of Durham*, Durham, United Kingdom.

`2000` **B.A., English Literature (First Class with distinction)**, *The University of Warwick*, Warwick, United Kingdom.

## Publications

{{< include list-of-publications_cv.qmd >}}

## Research projects

{{< include list-of-research-projects.qmd >}}

## Conference activity

### Organisation

`2019` "Central European Diasporas in Western Europe 15 years after the EU’s Eastern Enlargement: Political and Social Dynamics.” Workshop co-organised with Kacper Szulecki and Marta Bivand Erdal for the project *DIASPOlitic*, SWPS University, Warsaw, 6--7 November 2019.

"Internalising the Insurgency: Understanding the Interaction of Radical Antiestablishment and Mainstream Parties." Panel organised for the *ECPR General Conference*, Wrocław, 4--7 September 2019.

`2015` "Structures of political competition in post-communist democracies: if not cleavages, then what?” Workshop co-organised with Radosław Markowski for the *ECPR Joint Sessions of Workshops*, Warsaw, 29 March--2 April 2015.

`2014` “Crisis, Corruption and Cleavages: Continuities and Change in Party Politics in Central and Eastern Europe.” Panel organised for the *APSA Annual Meeting*, Washington, D.C., 28--31 August 2014.

### Participation
`2025` Pocketbook or Rosary Isn't Dead...It's Not Even Past! *PIASA Annual Meeting 2025*, Columbia University, 6th June 2025.

Democratic Hypocrisy in Practice: A panel study of revealed preferences for liberal democracy in Poland. *Interdisciplinary Seminar in Empirical Social Science*, University of Warsaw, 22nd January 2025.

`2024` Liberal democracy after the Good Change: the challenges of post-PiS reform in Poland. *ViPET seminar*, University of Vienna, 11 December 2024.

Liberal-democratic hypocrisy? Stability and change in Polish citizens’ attitudes towards liberal democracy. *ECPR General Conference*, Lisbon, 15 August 2024.

Liberal-democratic hypocrisy? Stability and change in Polish citizens’ attitudes towards liberal democracy. *5th International ESS Conference*, Lisbon, 9 July 2024.

Liberal-democratic hypocrisy? Stability and change in Polish citizens’ attitudes towards liberal democracy. *Workshop on Political Behaviour in Central and Eastern Europe*, European University Institute, Florence, 27 June 2024.

`2023` Lip-Service Liberalism? Declared and Revealed Attitudes to Democracy in Poland. *Grassroots Unrest in Europe and the Erosion of Liberal Democracy*, Illiberalism Studies Program, George Washington University\*, Washington, DC, 3 November 2023.

Polish Elections: What's Left of the Liberal Order? *Norwegian Institute of International Affairs (NUPI)*, Oslo, 29 September 2023.

Do Central European Diasporas Matter for Homeland Election Results? *Peace Research Institute (PRIO)*, Oslo, 28 September 2023.

You Are What You Eat: Edible Extremism and Cultural Polarisation in the Netherlands and Poland. *ECPR General Conference*, Prague, 4--8 September 2023.

Lip-Service Liberalism? Declared and Revealed Attitudes to Democracy in Poland. *APSA Annual Meeting*, Los Angeles, August 31--3 September 2023.

`2022` Squeezed from both sides: the dilemma of Poland’s social-democratic left. *European Forum on the Future of Political Parties: Between regeneration and decline – social democratic parties in Europe*, Rome, 15--16 September 2022.

Would democratic backsliders be elected to office if only CEE migrants voted? *19th IMISCOE International Conference*, Oslo, 29 June--1 July 2022.

`2021` When Populists Must Manage Crisis Instead of Performing It: COVID-19 in Poland. *VIII. Congress of The Czech Political Science Association*, Masaryk University, Brno, 9--10 September 2021.

External voting, diaspora party systems & (il)liberal remittances: A comparative analysis of Central European post-accession elections. *ECPR General Conference*, virtual event, 30 August--3 September 2021.

`2020` Populism and the Pandemic: Crisis, Technocracy and Democracy in Poland. *Populism and the Pandemic Virtual Lecture Series*, Jean Monnet EU Center for Comparative Populism, University of Wisconsin-Madison, 13 October 2020.

If Migrants Chose Governments: A Comparative Analysis of Central Eastern European Diaspora Votes, *ECPR General Conference*, virtual event, 24--28 August 2020.

`2019` Democratic Backsliding in Central and Eastern Europe: Transition to Illiberal Democracy? *TRASC: Europe--What’s Next? Transformational Leadership and Confidence Building for Young Professionals*, Georgian Institute for Strategic Studies (GISS), Tbilisi, 3--5 October 2019.

Inconsequential Radicalism: Explaining the Non-Impact of Poland’s Eurosceptic Turn on Public Attitudes to the EU; Illiberal Remittances? Studying the Political Dynamics and Voting Patterns of CEE Migrants in Western Europe. *ECPR General Conference*, Wrocław, 4--7 September 2019.

Dealing with the incumbency problem: designing a pilot study to improve populist attitude questions. *Comparative Populism Project closing conference*, Central European University, Budapest, 20 June 2019.

Inconsequential Radicalism: Explaining the Non-Impact of Poland’s Eurosceptic Turn on Public Attitudes to the EU; Central Europe’s Illiberal Turn: Causes, Consequences and Prospects, *EUSA International Biennial Conference*, Denver, 9--11 May 2019.

Conspiracy theory mentality and its socio-demographic and ideological correlates. *Workshop on "The Anatomy of Disbelief"*, Jagiellonian University, Kraków, 18 February 2019.

`2018` Populism in spite of the people? Confronting myths about Poland’s anti-liberal turn. *Conference on "Democracy, Illiberal Democracy or Neoauthoritarianism"*, Cardinal Stefan Wyszyński University, Warsaw, 28 November 2018.

The Growth of Populism in CEE? Invited lecture for the *Commission of Democracy workshop, Danish Youth Council*, Copenhagen, 26 November 2018.

Populism and Democracy in Poland. Invited lecture for the *IES Abroad European Union Programme*, Warsaw, 14 September 2018.

Working in the gaps left behind: radical right movement parties in a consolidating party system. *ECPR General Conference*, Hamburg, 22--25 August 2018.

Brexit: Explaining Britain’s decision to leave the European Union. Invited lecture at *Collegium Civitas*, Warsaw, 26 March 2018.

Voting Populist or Just Voting for Populists? A Comparative Analysis of Populist Attitudes and Vote Choice in Central and Eastern Europe. Invited lecture at the *Seminar in Politics and Society, Collegio Carlo Alberto*, Turin, 8 February 2018.

`2017` Populist voting, or just voting for populists? A comparative analysis of attitudes and voting behaviour in Central and Eastern Europe. Invited lecture at the Advanced Research Seminar, *Centre for Baltic and East European Studies, Södertörn University*, Stockholm, 13 November 2017.

Populism in Central and Eastern Europe. Invited lecture for the *Research Group in Populist Political Communication, Adam Mickiewicz University*, Poznań, 6--7 November 2017.

Voting Populist or Just Voting for Populists? A Comparative Analysis of Populist Attitudes and Vote Choice in Central and Eastern Europe. *Dilemmas of Democracy Conference*, Wisła, 26--27 October 2017.

Voting Populist or Just Voting for Populists? A Comparative Analysis of Populist Attitudes and Vote Choice in Central and Eastern Europe. *ECPR General Conference*, Oslo, 6--10 September 2017.

A New Populist Divide? Correspondences of Supply and Demand in the 2015 Polish Parliamentary Elections. *UACES 47th Annual Conference*, Kraków, 4--6 September 2017.

Voting Populist or Just Voting for Populists? A Comparative Analysis of Populist Attitudes and Vote Choice in Central and Eastern Europe. *3rd Prague Populism Conference*, Charles University, Prague, 22--23 May 2017.

Post-communist Populist Voting. 75th Annual MPSA Conference, Chicago, 6--9 April 2017.

`2016` A New Populist Divide? Correspondences of Supply and Demand in the 2015 Polish Parliamentary Elections. *Contemporary Political Parties Amid the Crisis of Democracy*, Turzno, 19–-20 October 2016.

Solidarism, Liberalism and Populism: voting behaviour in the 2015 Polish Parliamentary Elections. *ECPR General Conference*, Prague, 7--10 September 2016.

A new populist divide? Correspondences of supply and demand in the 2015 Polish parliamentary elections. *2nd Prague Populism Conference*, Prague, 23-24 May 2016.

`2015` The winner-loser divide in Central and Eastern Europe: a new set of political potentials? *ECPR Joint Sessions of Workshops*, Warsaw, 29 March--2 April 2015.

`2014` Eating the starters: The mainstreaming of populism in post-communist Poland. *ECPR General Conference*, Glasgow, 3--6 September 2014.

Integration for the Winners, Demarcation for the Losers? Poland A and Poland B as a Cleavage. *APSA Annual Meeting*, Washington, D.C., 28--31 August 2014.

Populism in Central and Eastern Europe. *Populism in Europe and the Americas: a cross-regional perspective*, Catholic University of Chile, Santiago, 4--5 July 2014.

The Dog That Already Barked: Post-Populism Crisis in Poland. *Populism in the Shadow of the Great Recession*, European University Institute, Florence, 21-22 March 2014.

`2013` Understanding the Palikot Movement. Invited seminar presentation at the *UCL School of Slavonic and East European Studies*, London, 4 February 2013.

`2012` From periphery to power: the emergence of Polish populism. *Studying Europe’s Populisms by Regional Country Clusters*, European University Institute, Florence, 7 December 2012.

The Thin Ideology of Populism. *Populist Political Parties in East Central Europe*, Masaryk University, Brno, 4 December 2012.

No Room On The Left? The Stagnation of Poland’s Democratic Left Alliance. *The financial crisis and left politics: Parties, unions, and social movements in Eastern Europe*, Charles University, Prague, 20 November 2012.

Down With the Pseudo-Elite! Populism as a Strategy for Elite Replacement in Post-Communist Poland. *International Political Science Association XXII World Congress of Political Science*, Madrid, 7--12 July 2012.

The Polish Self-Defence party: from agrarian protest to the politics of populism, 1990--2007. *Rural Protest Groups and Populist Political Parties: Exploring Objectives, Activities and Relationships*, University of Groningen, 24--25 May 2012.

`2011` Cleavage change or shapeless shifting? The dynamics of party-system supply and demand in Poland, 1997-2007. *Old Theory, New Cases, The Study of Party Politics in Central and Eastern Europe*, Södertörn University, Stockholm, 15--16 September 2011.

Cleavage change or shapeless shifting? The dynamics of party-system supply and demand in Poland, 1997--2007. *ECPR General Conference*, Reykjavik, 25--27 August 2011.

Eating the starters: the mainstreaming of Polish populism, 2001-2007. *18th Conference of Europeanists, Barcelona*, 20--22 June 2011.

Populism, Nationalism, or National Populism? An Analysis of Slovak Voting Behaviour in the 2010 Parliamentary Elections. *CBEES Departmental Seminar*, Södertörn University, Stockholm, 4 April 2011.

Change of government and the locus of politics--power shifts in post-communist Poland. *Change of government and the Locus of Politics: Power Shifts in the Baltic Sea Region*, Södertörn University, Stockholm, 13--14 January 2011.

`2010` The Polish presidential elections, June--July 2010: background and implications. *Free Elections 20 Years After: The Splendor and Misery of the Central European Dream*, Institute for Public Affairs and International Visegrad Fund, Bratislava, 8 July 2010.

Populism and its programmatic correlates in the Polish party system: a comprehensive classification. *ECPR Joint Sessions of Workshops*, Münster, 23--27 March 2010.

Voting for Polish populist anti-liberal parties: 1997--2005. *From post-communism and transitology to non-teleological change: present and future research on Eastern and Central Europe*, Södertörn University, 15--16 June 2009.

Populist Anti-liberal Ideology in the Polish Party System, 2001--2007. *Populism in Enlarged Europe*, Södertörn University, Stockholm 6--7 December 2007.

## Teaching

### Current academic year

Social Research Methodology (language of instruction: English)

Introduction to Political Psychology (English)

Challenges and Values in Public Life: Prejudice (Polish)

The Role of Conspiracy Theories in Public Life (Polish)

English in Professional Use (English)

The Social Psychology of Democracies in Transition (English)

The Social Psychology of Conspiracy Theories (English)

European Integration (Polish)

Student portfolio and thesis supervision (English)

### Previous seminars

Challenges and Values in Public Life: Polarisation (Polish)

Central and Eastern Europe During the Transition Period: Political, Economic and Social Changes of the Post-Communist Period

Oral Presentations

Professional Communications: Presentations

Professional Communications: Writing In Business

The Psychology of Prejudice

Populism, Nativism and the Problems of Contemporary Liberal Democracy

Social Psychology of Conspiracy Theories

Academic Writing

Introduction to Political Psychology

International Relations

European Politics

Politics of Governance: Eastern Europe

Contemporary Political Systems

Intellectual Property and Textual Composition

Regional Policy and the Structural Funds

The Polish Party System

### Previous lectures

Politics of Eastern Europe in Transition

Democracy in Europe

The Social Psychology of Democracies in Transition

European Integration

International Business and the Challenges of Globalization

Introduction to International Politics

Political Systems

Recent Polish Political History

Public Opinion

## Research training and skills

`2014` "Spatial Econometrics" and "Bayesian Analysis in the Social Sciences", *Essex Summer School in Social Science Data Analysis* 4--15 August 2014.

`2010` "Data analysis in R." *Essex Summer School in Social Science Data Analysis*, 26 July--6 August 2010.

"Workshop in Experimental Methods." *ELECDEM*, Brussels 28 June--2 July 2010.

"Workshop in Electoral Survey Design." *ELECDEM*, Central European University, Budapest, 30 April--4 May 2010.

`2009` Euromanifesto coder training, *Mannheim Centre for European Social Research*, University of Mannheim, 8--10 May 2009.

`2008` "Comparative research methods." *Essex Summer School in Social Science Data Analysis*, 7--18 July 2008.

## Other professional activities

### Awards

*East European Politics* Best Article Prize (shared with Mikołaj Cześnik), 2022.

Rector's Award for Scientific Achievements 2020/2021, SWPS University, 2021.

### Editorial

Deputy editor, *Polish Sociological Review*, 2025--present.

Member of the editorial advisory board: *Czech Journal of Political Science*, 2013--present; *Journal of Elections, Public Opinion and Parties*, 2016--present.

### Reviewing

Peer reviewer for *American Journal of Political Science*, *Cambridge Review of International Affairs*, *Comparative Political Studies*, *East European Politics*, *East European Politics and Societies*, *Europe-Asia Studies*, *European Journal of Political Research*, *German Politics*, *Government and Opposition*, *Journal of Elections, Public Opinion and Parties*, *Journal of European Integration*, *Journal of Legislative Studies*, *Party Politics*, *Perspectives on Politics*, *Political Research Exchange*, *Political Research Quarterly*, *Political Studies*, *Political Studies Review*, *Politics*, *Politics and Religion*, *Problems of Post-Communism*, *Representation.*

External reviewer of grant bid under *SASPRO Slovak Academy of Sciences Programme*, 2015.

### Thesis examination

Doctoral thesis, Paulina Lenik, "A pendulum swung back? Comparative analysis of populism in Central and Eastern Europe.", *University College London*, 2022.

Doctoral thesis, Justyna Lisińska, "How do populist supporters engage online?", *University of Southampton*, 2021.

Doctoral thesis, Agnieszka Sztajdel, "The Post-Truth Narrative in Post-Smolensk Poland", *European University Institute*, 2019.

### Miscellaneous

Member of the selection committee for the *ECPR Joint Sessions of Workshops*, 2019.

Member of the questionnaire committee for the Polish National Election Study 2015 post-electoral survey, *SWPS University*, 2015.

Member of the questionnaire committee for the CSES Slovakia 2010 post-electoral survey, *Institute of Sociology, Slovak Academy of Sciences*, 2010.

Manifesto coder for the Euromanifesto project, 2009.

Country coder for V-Dem (Varieties of Democracy), 2011--present.

## Languages

Native: English

Advanced: Polish
