---
editor: visual
---

# Ben Stanley Articles on Kultura Liberalna

**Total articles found:** 19

---

## [Analizy, opinie, wywiady, recenzje, felietony, eseje. Setki tekstów w otwartym dostępie. Skorzystaj z
            naszego archiwum!](https://kulturaliberalna.pl/tag/nr-810/)

**Date:** Date not found

*Nr 810 (30/2024) 19 lipca 2024 Jaki był przepis na sukces brytyjskiej lewicy? ...*

---

## [Analizy, opinie, wywiady, recenzje, felietony, eseje. Setki tekstów w otwartym dostępie. Skorzystaj z
            naszego archiwum!](https://kulturaliberalna.pl/tag/nr-788/)

**Date:** Date not found

*Nr 788 (7/2024) 19 lutego 2024 Czy Polacy popierają demokrację liberalną? ...*

---

## [Analizy, opinie, wywiady, recenzje, felietony, eseje. Setki tekstów w otwartym dostępie. Skorzystaj z
            naszego archiwum!](https://kulturaliberalna.pl/autor/ben-stanley/)

**Date:** Date not found

*Stały współpracownik „Kultury Liberalnej”. Profesor nadzwyczajny w Centrum Badań nad Demokracją na Uniwersytecie SWPS. Z wykształcenia politolog, uzyskał tytuł doktora na University of Essex i pracował w Instytucie Spraw Publicznych w Bratysławie, na Uniwersytecie Kardynała Stefana Wyszyńskiego w Wa...*

---

## [STANLEY: Raport z życia towarzyskiego: PiS wygrywa tam, gdzie nasi znajomi są tacy sami](https://kulturaliberalna.pl/2025/07/21/stanley-raport-z-zycia-towarzyskiego-pis-wygrywa-tam-gdzie-nasi-znajomi-sa-tacy-sami/)

**Date:** 21.07.2025

*Analiza polskich przyjaźni ukazuje społeczeństwo, w którym sprawy osobiste stały się głęboko polityczne. Z czysto wyborczego punktu widzenia w interesie PiS-u jest dalsza polaryzacja relacji społecznych. W przypadku KO jest dokładnie odwrotnie. Pisze Ben Stanley....*

---

## [Populizm przestał być marginesem](https://kulturaliberalna.pl/2025/06/24/populizm-przestal-byc-marginesem/)

**Date:** 24.06.2025

*Stało się to, co przewidział dwadzieścia lat temu Cas Mudde – populizm stał się dominującym, a nie marginalnym nurtem politycznym. Także w systemach partii umiarkowanych....*

---

## [Koalicja rządząca – małżeństwo z rozsądku na zakręcie](https://kulturaliberalna.pl/2025/06/03/koalicja-rzadzaca-malzenstwo-z-rozsadku-na-zakrecie/)

**Date:** 03.06.2025

*Niezachwiana pewność wygranej Rafała Trzaskowskiego w niedzielny wieczór jest symptomatyczna dla mentalności panującej w centrum polskiej sceny politycznej. Składa się na nią unikalne połączenie arogancji władzy ze zgubnym brakiem ciekawości przeciwników. Czołowi członkowie ugrupowania Trzaskowskieg...*

---

## [Prezydent Trzaskowski to koniec wymówek dla rządu](https://kulturaliberalna.pl/2025/05/26/prezydent-trzaskowski-to-koniec-wymowek-dla-rzadu/)

**Date:** 26.05.2025

*Podczas niedzielnego marszu Donald Tusk przepraszał za opieszałość swojego rządu w realizacji celów. Jego prośba o dostarczenie narzędzi niezbędnych do wykonania zadania ma sens. Premier powinien jednak bardzo poważnie potraktować uzasadniony sceptycyzm wyborców. Jeśli Rafał Trzaskowski wygra wybory...*

---

## [Najważniejsze słowa po pierwszej turze: strategia, mobilizacja, transfery](https://kulturaliberalna.pl/2025/05/16/najwazniejsze-slowa-po-pierwszej-turze-strategia-mobilizacja-transfery/)

**Date:** 16.05.2025

*Sukces Trzaskowskiego zależy od silnej mobilizacji w miastach, zwłaszcza w większych, jednak ich mieszkańcy stanowią tylko 12 procent elektoratu. Musi również utrzymać przewagę wśród kobiet (52 procent wyborców), jednocześnie pracując nad mieszkańcami wsi, których jest najwięcej. Proste....*

---

## [Jak to się stało, że radykalna prawica stała się tak silna?](https://kulturaliberalna.pl/2025/03/11/jak-to-sie-stalo-ze-radykalna-prawica-stala-sie-tak-silna/)

**Date:** 11.03.2025

*Sztucznie wytwarzane kryzysy systematycznie rekalibrują to, co społeczeństwa uważają za normalne. Robią to, tworząc środowiska polityczne, w których demokratyczny regres zachodzi bez zauważalnych, dramatycznych zmian, normy niegdyś uważane za nienaruszalne ślizgają się we wszystkich kierunkach, a mi...*

---

## [Czy Tusk może nie być populistą?](https://kulturaliberalna.pl/2025/01/14/czy-tusk-moze-nie-byc-populista/)

**Date:** 14.01.2025

*Mało kto w Polsce lub za granicą zaklasyfikowałby koalicję rządzącą jako populistyczną. Przy wszystkich wodzowskich i apodyktycznych tendencjach Tuska pozostaje on w stylu i tonie bliższy swoim liberalnym współbraciom niż Le Pen, Meloni czy Orbánowi. Jednak widać, że Polska będzie zwiastunem zmian, ...*

---

## [Państwo w okresie przejściowym](https://kulturaliberalna.pl/2024/10/15/panstwo-w-okresie-przejsciowym/)

**Date:** 15.10.2024

*Nieliberalne rządy spowodowały trwałe zmiany w oczekiwaniach społecznych dotyczących roli i możliwości demokracji. Tworzą one strukturalne ograniczenia dla kolejnych rządów. To zmusza Donalda Tuska do zrównoważenia liberalno-demokratycznych zasad z populistycznymi żądaniami społeczeństwa....*

---

## [STANLEY: Demokracja walcząca – szansa czy zagrożenie?](https://kulturaliberalna.pl/2024/09/24/demokracja-walczaca-szansa-czy-zagrozenie/)

**Date:** 24.09.2024

*Koncepcja „demokracji walczącej” to proaktywne działania podejmowane przez władzę, mające na celu ochronę systemu demokratycznego przed jego wrogami. Mogą one na przykład oznaczać wdrożenie przepisów zakazujących działalności niektórych partii lub organizacji politycznych, ograniczając w ten sposób ...*

---

## [Wielka Brytania ma problem z imigracją, ale to nie tłumaczy zamieszek](https://kulturaliberalna.pl/2024/08/14/stanley-wielka-brytania-ma-problem-z-imigracja-ale-to-nie-tlumaczy-zamieszek/)

**Date:** 14.08.2024

*Zamieszki z sierpnia 2024 roku nie wydarzyły się w próżni. Doprowadził do nich nie tylko gniew z powodu imigracji, ale także sprzeciw wobec gospodarczego i społecznego upadku Wielkiej Brytanii. Era oszczędności pod rządami kolejnych konserwatywnych rządów zaowocowała spadkiem wydajności władz lokaln...*

---

## [STANLEY: Jaki był przepis na sukces brytyjskiej lewicy?](https://kulturaliberalna.pl/2024/07/19/jaki-byl-przepis-na-sukces-brytyjskiej-lewicy/)

**Date:** 19.07.2024

*Partia Pracy w przeszłości znajdowała się pod rządami polityków, którzy byli uważani za osobiście przyzwoitych, ale politycznie mało inspirujących (Ed Miliband), albo za niedopuszczalnie radykalnych (Jeremy Corbyn). Wraz z końcem ery zdefiniowanej przez oszczędności i pogoń za radykalnie prawicową p...*

---

## [Czym grozi demokracja hipokrytów?](https://kulturaliberalna.pl/2024/06/04/czym-grozi-demokracja-hipokrytow/)

**Date:** 04.06.2024

*Wyrażając swoje zniecierpliwienie względem działań rządu, niektórzy z jego zwolenników (tak zwani „silni razem”) sugerują pewną tolerancję – jeśli nie wręcz zachętę – dla idei naginania zasad w celu szybszego osiągnięcia rezultatów. Jednocześnie, w niektórych kręgach obecnej opozycji można dostrzec ...*

---

## [STANLEY: Technokracja to zaprzeczenie demokracji przedstawicielskiej](https://kulturaliberalna.pl/2024/04/29/stanley-technokracja-to-zaprzeczenie-demokracji-przedstawicielskiej/)

**Date:** 29.04.2024

*Podczas gdy wszystkie rządy polegają na poradach ekspertów, technokracja doprowadzona do skrajności jest sprzeczna z demokracją przedstawicielską. W okolicznościach, w których zwłaszcza zwolennicy PiS-u przyzwyczaili się do rządów potężnej władzy wykonawczej, która ignoruje ograniczenia, aby osiągną...*

---

## [STANLEY: Temat aborcji przesądził o wyborach. Koalicja rządząca nie może zamieść go pod dywan](https://kulturaliberalna.pl/2024/04/05/stanley-temat-aborcji-przesadzil-o-wyborach-koalicja-rzadzaca-nie-moze-zamiesc-go-pod-dywan/)

**Date:** 05.04.2024

*Aborcja była ważnym czynnikiem decydującym o tym, na kogo głosowały Polki i Polacy w wyborach parlamentarnych 15 października. Dlatego spór o aborcję wewnątrz koalicji rządzącej nie zostanie łatwo zamieciony pod dywan....*

---

## [STANLEY: Nie ufamy wyborcom PiS-u tak samo, jak nie ufamy PiS-owi. To problem dla naszej demokracji](https://kulturaliberalna.pl/2024/03/19/nie-ufamy-wyborcom-pis-u-tak-samo-jak-nie-ufamy-pis-owi-to-problem-dla-naszej-demokracji/)

**Date:** 19.03.2024

*W Polsce poziom niechęci wobec wyborców partii przeciwnej jest równie wysoki jak niechęć wobec samej tej partii i jej kandydatów. W sytuacji tak głębokiej nieufności społecznej trudno wyobrazić sobie udane odrodzenie pluralistycznej demokracji....*

---

## [STANLEY: Czy Polacy popierają demokrację liberalną?](https://kulturaliberalna.pl/2024/02/19/stanley-czy-polacy-popieraja-demokracje-liberalna/)

**Date:** 19.02.2024

*Według nowych badań przeciętny Polak umiarkowanie popiera demokrację liberalną, z wynikiem 0,62. Przeciętny zwolennik PiS-u jest jej mniej przychylny (0,50) niż ogół Polaków. Z kolei zwolennicy KO (0,72) i Lewicy (0,72) popierają demokrację liberalną bardziej niż większość....*

---


