---
editor: visual
---

### Current projects

`2023-2025` Co-investigator, Work Packages 2 and 4, “AUTHLIB – Neo-Authoritarianisms in Europe and the Liberal Democratic Response”, *HORIZON-CL2-2021-DEMOCRACY-01*, €2,523,765.

`2021-2024` Principal investigator, “Plemienność czy obojętność? Badanie rzeczywiście istniejących wartości demokratycznych i ich konsekwencji w Polsce” (“Partisan bias or a climate of indifference? An investigation of actually-existing democratic values and their consequences in Poland”), *National Science Center, OPUS 20*, 783,228 zł.

### Previous projects

`2022` Co-investigator, “Wiedza, postawy i preferencje Polek i Polaków względem nowych zagrożeń cywilizacyjnych.” (“Political knowledge and preferences of Poles regarding new civilisational threats.”), *Regionalna Inicjatywa Doskonałości w SWPS Uniwersytecie Humanistycznospołecznym w latach 2019-2022*, 118,770 zł.

`2019-2021` Principal investigator, “DIASPOlitic: Understanding the Political Dynamics of Émigré Communities in an Era of European Democratic Backsliding”, *Norwegian Research Council, EUROPA (Europe in Transitions) A2–Values Under Pressure*, 221,880 zł.

`2019-2020` Principal investigator, “Mierząc populizm: badanie pilotażowe mające na celu udoskonalenie istniejących pytań”. (“Measuring populism: a pilot study to improve existing questions.”) *Narodowe Centrum Nauki, MINIATURA 2, \[2018/02/X/HS5/03339\]*, 43,972 zł.

`2017-2018` Principal investigator, “A Survey-Based Experiment on the Relationship Between Populism and Conspiracy Theories”, *SWPS University BST grant*, 26876 zł.

`2013-2015` Principal investigator, “The Winner-Loser Divide? A Comparative Analysis of Voting Behaviour and Cleavage Formation in Post-Communist Party Systems (WINLOSE)”. Project funded by *Marie Curie Intra-European Fellowship* programme, a Marie Curie Action under the Seventh Framework Programme, €231,283.

`2010` Principal investigator, “Integration versus Demarcation? A Comparative Classification of Party Appeals, Voter Preferences and Candidate Attitudes in the European Parliamentary Elections of 2009”. Project conducted under the *ELECDEM Initial Training Network (ref. 238607)*, a Marie Curie Action under the Seventh Framework Programme, £68,290.
