---
title: "Media"
editor: visual
---

### Kultura Liberalna

-   [Czy Tusk może nie być populistą?](https://kulturaliberalna.pl/2025/01/14/czy-tusk-moze-nie-byc-populista/) (14.01.2025)

-   [Państwo w okresie przejściowym](https://kulturaliberalna.pl/2024/10/15/panstwo-w-okresie-przejsciowym/) (15.10.2024)

-   [Demokracja walcząca -- szansa czy zagrożenie?](https://kulturaliberalna.pl/2024/08/14/stanley-wielka-brytania-ma-problem-z-imigracja-ale-to-nie-tlumaczy-zamieszek/) (24.09.2024)

-   [Wielka Brytania ma problem z imigracją, ale to nie tłumaczy zamieszek](https://kulturaliberalna.pl/2024/08/14/stanley-wielka-brytania-ma-problem-z-imigracja-ale-to-nie-tlumaczy-zamieszek/) (14.08.2024)

-   [Czym grozi demokracja hipokrytów?](https://kulturaliberalna.pl/2024/06/04/czym-grozi-demokracja-hipokrytow/) (04.06.2024)

-   [Technokracja to zaprzeczenie demokracji przedstawicielskiej](https://kulturaliberalna.pl/2024/04/29/stanley-technokracja-to-zaprzeczenie-demokracji-przedstawicielskiej/) (29.04.2024)

-   [Temat aborcji przesądził o wyborach. Koalicja rządząca nie może zamieść go pod dywan](https://kulturaliberalna.pl/2024/04/05/stanley-temat-aborcji-przesadzil-o-wyborach-koalicja-rzadzaca-nie-moze-zamiesc-go-pod-dywan/) (05.04.2024)

-   [Nie ufamy wyborcom PiS-u tak samo, jak nie ufamy PiS-owi. To problem dla naszej demokracji](https://kulturaliberalna.pl/2024/03/19/nie-ufamy-wyborcom-pis-u-tak-samo-jak-nie-ufamy-pis-owi-to-problem-dla-naszej-demokracji/) (19.03.2024)

-   [Czy Polacy popierają demokrację liberalną?](https://kulturaliberalna.pl/2024/02/19/stanley-czy-polacy-popieraja-demokracje-liberalna/) (19.02.2024)

-   [Populizm pozostanie polityką dla ludzi sfrustrowanych](https://kulturaliberalna.pl/2024/01/30/populizm-pozostanie-polityka-dla-ludzi-sfrustrowanych/) (30.01.2024)

### Polityka.pl

-   [Co pokazują najnowsze sondaże? Władza dla PiS z Konfederacją czy dla opozycji?](https://www.polityka.pl/tygodnikpolityka/kraj/2229078,1,co-pokazuja-najnowsze-sondaze-wladza-dla-pis-z-konfederacja-czy-dla-opozycji.read) (27.09.2023)

-   [Sondaże w połowie września. PiS rośnie, Konfederacja słabnie. Co z tego wynika?](https://www.polityka.pl/tygodnikpolityka/kraj/2227338,1,sondaze-w-polowie-wrzesnia-pis-rosnie-konfederacja-slabnie-co-z-tego-wynika.read) (14.09.2023)

-   [Sierpniowe sondaże. PiS trochę w górę, KO się trzyma, Konfederacja gaśnie](https://www.polityka.pl/tygodnikpolityka/kraj/2225160,1,sierpniowe-sondaze-pis-troche-w-gore-ko-sie-trzyma-konfederacja-gasnie.read) (28.08.2023)

-   [KO może wyprzedzić PiS w sondażach. Ale czy to da opozycji władzę?](https://www.polityka.pl/tygodnikpolityka/kraj/2220810,1,ko-moze-wyprzedzic-pis-w-sondazach-ale-czy-to-da-opozycji-wladze.read) (21.07.2023)

-   [Co pokazują sondaże? KO blisko PiS, ale niekoniecznie bliżej władzy](https://www.polityka.pl/tygodnikpolityka/kraj/2217564,1,co-pokazuja-sondaze-ko-blisko-pis-ale-niekoniecznie-blizej-wladzy.read) (27.06.2023)

-   [Sondaże po 4 czerwca. Obóz demokratyczny (na razie) nie zyskał](https://www.polityka.pl/tygodnikpolityka/kraj/2216098,1,sondaze-po-4-czerwca-oboz-demokratyczny-na-razie-nie-zyskal.read) (15.06.2023)

-   [Sojusz PSL i Hołowni w sondażach. Sukces czy porażka?](https://www.polityka.pl/tygodnikpolityka/kraj/2214326,1,sojusz-psl-i-holowni-w-sondazach-sukces-czy-porazka.read) (31.05.2023)

-   [Wybory do Sejmu na ostrzu noża. Sondaże o koalicji PSL-Polska 2050.](https://www.polityka.pl/tygodnikpolityka/kraj/2210842,1,wybory-do-sejmu-na-ostrzu-noza-sondaze-o-koalicji-psl-polska-2050.read) (28.04.2023)

-   [Wnioski z ostatnich sondaży. Silniejsza Konfederacja: dla kogo to jest teraz wyzwanie.](https://www.polityka.pl/tygodnikpolityka/kraj/2208024,1,wnioski-z-ostatnich-sondazy-silniejsza-konfederacja-dla-kogo-to-jest-teraz-wyzwanie.read) (05.04.2023)

-   [Sondaże po lutym. Umacnia się dominacja PiS i Koalicji Obywatelskiej.](https://www.polityka.pl/tygodnikpolityka/kraj/2203626,1,sondaze-po-lutym-umacnia-sie-dominacja-pis-i-koalicji-obywatelskiej.read) (01.03.2023)

-   [Sondaże jak VAR. Koalicja Obywatelska coraz bliżej PiS.](https://www.polityka.pl/tygodnikpolityka/kraj/2199500,1,sondaze-jak-var-koalicja-obywatelska-coraz-blizej-pis.read) (27.01.2023)

-   [Kto w końcu prowadzi w sondażach? Odcinamy szum.](https://www.polityka.pl/tygodnikpolityka/kraj/2193686,1,kto-w-koncu-prowadzi-w-sondazach-odcinamy-szum.read) (13.12.2022)

-   [KO wyprzedza PiS w sondażach? Jeszcze nie teraz, ale…](https://www.polityka.pl/tygodnikpolityka/kraj/2186994,1,ko-wyprzedza-pis-w-sondazach-jeszcze-nie-teraz-ale.read) (25.10.2022)

-   [PiS traci aurę nietykalności. Opozycja w sondażach bliżej władzy.](https://www.polityka.pl/tygodnikpolityka/kraj/2182024,1,pis-traci-aure-nietykalnosci-opozycja-w-sondazach-blizej-wladzy.read) (19.09.2022)

-   [Przełom w partyjnych sondażach? Nie tym razem. Trzy powody.](https://www.polityka.pl/tygodnikpolityka/kraj/2175811,1,przelom-w-partyjnych-sondazach-nie-tym-razem-trzy-powody.read?src=mt) (01.08.2022)

-   [Co słychać w sondażach? Wraca system dwóch (i pół) partii.](https://www.polityka.pl/tygodnikpolityka/kraj/2165629,1,co-slychac-w-sondazach-wraca-system-dwoch-i-pol-partii.read) (13.05.2022)

-   [Sondaże z początku roku. Polska 2050 i PSL nieco w górę. Co z PiS?](https://www.polityka.pl/tygodnikpolityka/kraj/2151110,1,sondaze-z-poczatku-roku-polska-2050-i-psl-nieco-w-gore-co-z-pis.read) (11.04.2022)

-   [Rok w sondażach. Wróciliśmy do punktu wyjścia, ale patrzmy na trendy.](https://www.polityka.pl/tygodnikpolityka/kraj/2149542,1,rok-w-sondazach-wrocilismy-do-punktu-wyjscia-ale-patrzmy-na-trendy.read) (01.01.2022)

-   [PiS i KO tracą w sondażach. To kto zyskuje?](https://www.polityka.pl/tygodnikpolityka/kraj/2144644,1,pis-i-ko-traca-w-sondazach-to-kto-zyskuje.read) (24.11.2021)

-   [Duży spadek PiS w sondażu CBOS. To przełom?](https://www.polityka.pl/tygodnikpolityka/kraj/2141692,1,duzy-spadek-pis-w-sondazu-cbos-to-przelom.read) (03.11.2021)

-   [Mimo groźby polexitu PiS wciąż rośnie w sondażach.](https://www.polityka.pl/tygodnikpolityka/kraj/2139238,1,mimo-grozby-polexitu-pis-wciaz-rosnie-w-sondazach.read) (15.10.2021)

-   [KO silniejsza w sondażach, ale opozycja słabsza.](https://www.polityka.pl/tygodnikpolityka/kraj/2134122,1,ko-silniejsza-w-sondazach-ale-opozycja-slabsza.read) (09.09.2021)

-   [Więcej niż efekt Tuska. KO rośnie w sondażach, PiS buksuje w miejscu.](https://www.polityka.pl/tygodnikpolityka/kraj/2128493,1,wiecej-niz-efekt-tuska-ko-rosnie-w-sondazach-pis-buksuje-w-miejscu.read) (02.08.2021)

-   [Efekt Tuska już widać w sondażach. Koalicja Obywatelska wraca na drugie miejsce.](https://www.polityka.pl/tygodnikpolityka/kraj/2126089,1,efekt-tuska-juz-widac-w-sondazach-koalicja-obywatelska-wraca-na-drugie-miejsce.read) (15.07.2021)

-   [Lewica w sondażach nie zyskała, PO nie przestała tracić.](https://www.polityka.pl/tygodnikpolityka/kraj/2118683,1,lewica-w-sondazach-nie-zyskala-po-nie-przestala-tracic.read?src=mt) (15.05.2021)

-   [Władza kontra opozycja, KO kontra Hołownia. Co mówią sondaże?](https://www.polityka.pl/tygodnikpolityka/kraj/2106033,1,wladza-kontra-opozycja-ko-kontra-holownia-co-mowia-sondaze.read) (23.02.2021)

-   [PiS bez samodzielnej większości, Hołownia tuż za KO.](https://www.polityka.pl/tygodnikpolityka/kraj/2101969,1,pis-bez-samodzielnej-wiekszosci-holownia-tuz-za-ko.read?src=mt) (02.02.2021)

-   [Nie tylko aborcja. O co chodzi zwolennikom Strajku Kobiet?](https://www.polityka.pl/tygodnikpolityka/kraj/2101249,1,nie-tylko-aborcja-o-co-chodzi-zwolennikom-strajku-kobiet.read) (30.01.2021)

-   [PiS odrabia straty w sondażach. Zyskuje też Hołownia i Lewica.](https://www.polityka.pl/tygodnikpolityka/kraj/2097207,1,pis-odrabia-straty-w-sondazach-zyskuje-tez-holownia-i-lewica.read)(31.12.2020)

-   [Sondaż w sprawie protestów. Kto bierze udział w spacerach?](https://www.polityka.pl/tygodnikpolityka/kraj/2074683,1,sondaz-w-sprawie-protestow-kto-bierze-udzial-w-spacerach.read)\[with Marta Żerkowska-Balas\] (30.12.2020)

-   [PiS wyraźnie traci, opozycja mogłaby stworzyć rząd.](https://www.polityka.pl/tygodnikpolityka/kraj/1980356,1,pis-wyraznie-traci-opozycja-moglaby-stworzyc-rzad.read) (26.11.2020)

-   [PiS wyraźnie stracił w sondażach. Kto na tym zyskał?](https://www.polityka.pl/tygodnikpolityka/kraj/1978128,1,pis-wyraznie-stracil-w-sondazach-kto-na-tym-zyskal.read)(06.11.2020)

-   [Dobre sondaże KO. Ruch Hołowni może jej zaszkodzić.](https://www.polityka.pl/tygodnikpolityka/kraj/1968042,1,dobre-sondaze-ko-ruch-holowni-moze-jej-zaszkodzic.read) (18.09.2020)

-   [Ostatnie sondaże w tej kampanii. Trzaskowski o włos przed Dudą?](https://www.polityka.pl/tygodnikpolityka/kraj/1963436,1,ostatnie-sondaze-w-tej-kampanii-trzaskowski-o-wlos-przed-duda.read)(10.07.2020)

-   [Duda minimalnie przed Trzaskowskim, ale do rozstrzygnięcia daleko](https://www.polityka.pl/tygodnikpolityka/kraj/1962464,1,duda-minimalnie-przed-trzaskowskim-ale-do-rozstrzygniecia-daleko.read?src=mt). (03.07.2020)

-   [Sondaże: Duda z Trzaskowskim w drugiej turze. Ile ich dzieli?](https://www.polityka.pl/tygodnikpolityka/kraj/1961566,1,sondaze-duda-z-trzaskowskim-w-drugiej-turze-ile-ich-dzieli.read) (26.06.2020)

-   [W drugiej turze Trzaskowski już remisuje z Dudą](https://www.polityka.pl/tygodnikpolityka/kraj/1960778,1,stanley-dla-polityki-w-drugiej-turze-trzaskowski-juz-remisuje-z-duda.read?src=mt). (19.06.2020)

-   [W sondażach drugiej tury z Dudą coraz gorzej](https://www.polityka.pl/tygodnikpolityka/kraj/1959686,1,w-sondazach-drugiej-tury-z-duda-coraz-gorzej.read?src=mt). (09.06.2020)

-   [Trzaskowski wchodzi do gry. Co widać w sondażach?](https://www.polityka.pl/tygodnikpolityka/kraj/1957640,1,trzaskowski-wchodzi-do-gry-co-widac-w-sondazach.read) (22.05.2020)

-   [Co widać w sondażach? Duda wygrywa przy niskiej frekwencji.](https://www.polityka.pl/tygodnikpolityka/kraj/1954530,1,co-widac-w-sondazach-duda-wygrywa-przy-niskiej-frekwencji.read) (29.04.2020)

-   [Rząd dezinformuje o Unii. Czy Polacy mu wierzą?](https://www.polityka.pl/tygodnikpolityka/kraj/1953522,1,rzad-dezinformuje-o-unii-czy-polacy-mu-wierza.read) (22.04.2020)

-   [Stanley dla „Polityki”: Duda wciąż faworytem, ale drugiej tury](https://www.polityka.pl/tygodnikpolityka/kraj/1949534,1,stanley-dla-polityki-duda-wciaz-faworytem-ale-drugiej-tury.read). (25.03.2020)

### Other

-   [The Ambivalence of Polish Populism](https://europe.columbia.edu/content/rise-and-resilience-populism-eastern-europe) \[*Rise and Resilience of Populism in Eastern Europe, Columbia European Institute*, interviewed\] (20.01.2022)

-   [Polish president vetoes controversial media law decried by U.S.](https://www.washingtonpost.com/world/2021/12/27/poland-media-law-duda/) \[*The Washington Post*, interviewed\] (27.12.2021)

-   [‘A backlash against a patriarchal culture’: How Polish protests go beyond abortion rights.](https://www.theguardian.com/world/2020/nov/06/a-backlash-against-a-patriarchal-culture-how-polish-protests-go-beyond-abortion-rights) \[*The Guardian*, interviewed\] (06.11.2020)

-   [Erosão contínua da democracia na Hungria e na Polônia provoca impasse na União Europeia.](https://oglobo.globo.com/mundo/erosao-continua-da-democracia-na-hungria-na-polonia-provoca-impasse-na-uniao-europeia-1-24709374)\[*O Globo*, interviewed\] (24.10.2020)

-   [What’s at stake as Kaczynski returns to Poland’s front line?](https://www.ft.com/content/d504c841-d1e5-4a7d-9d7c-e2a2ed9f6fe1) \[*Financial Times*, interviewed\] (01.10.2020)

-   [Law & Justice loses touch with Poland’s moderate Catholics.](https://www.ft.com/content/640bc895-8232-4225-9a95-363a779ff531)\[*Financial Times*, interviewed\] (28.09.2020)

-   [Poland heads for presidential run-off.](https://www.ft.com/content/570e24f9-057c-4a39-b81c-7f90e1eb6f85) \[*Financial Times*, interviewed\] (29.06.2020)

-   [Czego brakuje Polakom? Odpowiada brytyjski politolog mieszkający w Polsce. ](https://www.newsweek.pl/ben-stanley-brytyjski-politolog-o-dumie-z-polski-rozmowa/8jtd8t6)\[Newsweek, interviewed\] (16.12.2018)
