### Recent

Bill, Stanley, and Ben Stanley. 2025. ‘Democracy After Illiberalism: A Warning from Poland’. *Journal of Democracy* 36(3): 16–32.

Claassen, Christopher, Kathrin Ackermann, Eri Bertsou, Lucas Borba, Ryan E. Carlin, Amnon Cavari, Sirianne Dahlum, et al. 2025. ‘Conceptualizing and Measuring Support for Democracy: A New Approach’. *Comparative Political Studies* 58(6): 1171–98. doi:[10.1177/00104140241259458](https://doi.org/10.1177/00104140241259458).

Enyedi, Zsolt, and Ben Stanley. 2025. ‘Farewell to the Liberal Consensus: The Intellectualisation of Political Projects in Poland and Hungary’. *European Political Science*. doi:[10.1057/s41304-025-00542-8](https://doi.org/10.1057/s41304-025-00542-8).

Bill, Stanley and Ben Stanley. 2025. *Good Change: The Rise and Fall of Poland's Illiberal Revolution*. Stanford University Press. [https://www.sup.org/books/politics/good-change/](https://www.sup.org/books/politics/good-change/).

Stanley, Ben, 2025. 'Political Parties and Ideological Representation'. In *The Oxford Handbook of Polish Politics*, eds. Katarzyna Walecka, Simona Guerra, and Fernando Casal Bértoa. Oxford University Press.

---

