// AUTO-GENERATED by scripts/sync-teaching.py from the Teaching repo.
// Do not edit by hand — re-run build.sh (or the script) to regenerate.

#set document(title: "Dziennikarstwo danych")
#metadata((title: "Dziennikarstwo danych")) <website-metadata>

#html.elem("p", attrs: (class: "teaching-back"))[#link("../teaching.html", "← All courses")]

#heading(level: 1)[#"Dziennikarstwo danych"]

#heading(level: 2)[#"Slajdy"]

#enum(
  { link("https://bdstanley.netlify.app/dziennikarstwo-danych-1-slides", "Czym jest a czym nie jest dziennikarstwo danych") },
  { link("https://bdstanley.netlify.app/dziennikarstwo-danych-2-slides", "Po co nam kolejny gatunek dziennikarstwa?") },
  { link("https://bdstanley.netlify.app/dziennikarstwo-danych-3-slides", "Skąd brać dane w data journalism?") },
  { link("https://bdstanley.netlify.app/dziennikarstwo-danych-4-slides", "Proces analizy danych i narzędzia") },
  { link("https://bdstanley.netlify.app/dziennikarstwo-danych-5-slides", "Wizualizacja danych: zasady, narzędzia") },
  { link("https://bdstanley.netlify.app/dziennikarstwo-danych-6-slides", "Krytyka dziennikarstwa danych / Pułapki dziennikarstwa danych") },
)

#heading(level: 2)[#"Ćwiczenia"]

#list(
  { link("https://bdstanley.netlify.app/dziennikarstwo-danych-2-exercise-1", "Ćwiczenie 1: Identyfikacja tematów wymagających dziennikarstwa danych") + [#" · "] + link("https://bdstanley.netlify.app/dziennikarstwo-danych-2-exercise-1-answers", "answers") },
  { link("https://bdstanley.netlify.app/dziennikarstwo-danych-2-exercise-2", "Ćwiczenie 2: Wybór tematu projektu końcowego") },
  { link("https://bdstanley.netlify.app/dziennikarstwo-danych-3-exercise", "Ćwiczenie grupowe: workflow pozyskiwania danych") },
  { link("https://bdstanley.netlify.app/dziennikarstwo-danych-6-exercise", "Identyfikacja ryzyk projektu") },
)
