// AUTO-GENERATED by scripts/sync-teaching.py from the Teaching repo.
// Do not edit by hand — re-run build.sh (or the script) to regenerate.

#set document(title: "English for Professional Purposes")
#metadata((title: "English for Professional Purposes")) <website-metadata>

#html.elem("p", attrs: (class: "teaching-back"))[#link("../teaching.html", "← All courses")]

#heading(level: 1)[#"English for Professional Purposes"]
