// AUTO-GENERATED by scripts/sync-teaching.py from the Teaching repo.
// Do not edit by hand — re-run build.sh (or the script) to regenerate.

#set document(title: "English for Professional Purposes")
#metadata((title: "English for Professional Purposes")) <website-metadata>

#html.elem("p", attrs: (class: "teaching-back"))[#link("../teaching.html", "← All courses")]

#heading(level: 1)[#"English for Professional Purposes"]

#heading(level: 2)[#"Slides"]

#enum(
  { link("https://bdstanley.netlify.app/english-professional-purposes-1-slides", "Course introduction / Globalization of the economy") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-2-slides", "Types of business entities") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-3-slides", "Types of business entities") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-4-slides", "The grammar of cause and effect in business communication") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-5-slides", "Culture and ethics") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-6-slides", "Management and leadership styles") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-7-slides", "Finance of organisations") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-8-slides", "Active vs. passive voice in people management") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-9-slides", "Speaking skills 1: presentations") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-10-slides", "Speaking skills 2: introduction and presentation of the company profile; calls; negotiations") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-11-slides", "Writing skills") },
)

#heading(level: 2)[#"Exercises"]

#list(
  { link("https://bdstanley.netlify.app/english-professional-purposes-1-exercise-comprehension", "Reading: global economic shifts") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-1-exercise-grammar", "Grammar: perfect tenses") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-1-exercise-vocabulary", "Vocabulary: trade and globalisation") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-2-exercise-handout", "Comprehension, grammar and vocabulary: small businesses") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-2-exercise-reading-text", "Reading: are small businesses in big trouble?") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-3-exercise-comprehension-text", "Reading: business strategies for a coffee startup") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-3-exercise-grammar-vocabulary", "Sentence adverbials and business vocabulary") + [#" · "] + link("https://bdstanley.netlify.app/english-professional-purposes-3-exercise-grammar-vocabulary-answers", "answers") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-3-exercise-handout", "Comprehension, grammar and vocabulary tasks") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-3-exercise-listening-questions", "Listening questions: the fall of Innovatek") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-3-exercise-listening-script", "Listening script: the fall of Innovatek") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-4-exercise-writing", "Recommending an organisational structure") + [#" · "] + link("https://bdstanley.netlify.app/english-professional-purposes-4-exercise-writing-answers", "answers") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-5-exercise-grammar-vocabulary", "Ethics vocabulary and modal verbs") + [#" · "] + link("https://bdstanley.netlify.app/english-professional-purposes-5-exercise-grammar-vocabulary-answers", "answers") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-5-exercise-group-1", "Group work: profit-focused shareholders (group 1)") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-5-exercise-group-2", "Group work: balanced approach shareholders (group 2)") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-5-exercise-group-3", "Group work: values-driven shareholders (group 3)") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-5-exercise-group-text", "Reading: from idealism to honest coffee") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-6-exercise-case-study", "Choosing a management style") + [#" · "] + link("https://bdstanley.netlify.app/english-professional-purposes-6-exercise-case-study-answers", "answers") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-6-exercise-grammar-vocabulary", "Word forms in leadership vocabulary") + [#" · "] + link("https://bdstanley.netlify.app/english-professional-purposes-6-exercise-grammar-vocabulary-answers", "answers") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-7-exercise-grammar-vocabulary", "Finance vocabulary and reported speech") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-8-exercise-grammar", "Grammar: active and passive voice") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-8-exercise-group", "Evaluating employee misconduct") + [#" · "] + link("https://bdstanley.netlify.app/english-professional-purposes-8-exercise-group-answers", "answers") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-10-exercise-group-1", "Company profile presentation (group 1): CloudTech Solutions") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-10-exercise-group-2", "Company profile presentation (group 2): GreenField Manufacturing") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-10-exercise-group-3", "Company profile presentation (group 3): Heritage Financial Services") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-10-exercise-group-4", "Company profile presentation (group 4): MediTech Innovations") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-11-exercise-business-proposal-1", "Business proposal 1: cloud migration") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-11-exercise-business-proposal-2", "Business proposal 2: sustainable office transformation") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-11-exercise-business-proposal-3", "Business proposal 3: customer data analytics") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-11-exercise-group-1", "Six phases of negotiation (group 1)") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-11-exercise-group-2", "Six phases of negotiation (group 2)") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-11-exercise-group-3", "Six phases of negotiation (group 3)") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-11-exercise-group-4", "Six phases of negotiation (group 4)") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-11-exercise-memo-1", "Memo 1: new expense claim procedures") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-11-exercise-memo-2", "Memo 2: company rebrand") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-11-exercise-memo-3", "Memo 3: hot-desking policy") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-12-exercise-group-1", "Market research analysis: Meridian Consulting report (Group 1)") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-12-exercise-group-2", "Market research analysis: Thornfield Advisory report (Group 2)") },
  { link("https://bdstanley.netlify.app/english-professional-purposes-12-exercise-group-3", "Market research analysis: Strategic Insights Partnership report (Group 3)") },
)
