// AUTO-GENERATED by scripts/sync-teaching.py from the Teaching repo.
// Do not edit by hand — re-run build.sh (or the script) to regenerate.

#set document(title: "Język angielski w zastosowaniu zawodowym")
#metadata((title: "Język angielski w zastosowaniu zawodowym")) <website-metadata>

#html.elem("p", attrs: (class: "teaching-back"))[#link("../teaching.html", "← All courses")]

#heading(level: 1)[#"Język angielski w zastosowaniu zawodowym"]

#heading(level: 2)[#"Slajdy"]

#enum(
  { link("https://bdstanley.netlify.app/jezyk-angielski-1-slides", "Wprowadzenie i podstawy biznesu") },
  { link("https://bdstanley.netlify.app/jezyk-angielski-2-slides", "Strategie i struktura") },
  { link("https://bdstanley.netlify.app/jezyk-angielski-3-slides", "Kultura organizacyjna i przywództwo") },
  { link("https://bdstanley.netlify.app/jezyk-angielski-4-slides", "Finanse, ludzie i innowacje") },
  { link("https://bdstanley.netlify.app/jezyk-angielski-5-slides", "Umiejętności pisania zawodowego") },
  { link("https://bdstanley.netlify.app/jezyk-angielski-6-slides", "Umiejętności komunikacji ustnej") },
)

#heading(level: 2)[#"Materiały"]

#list(
  { link("https://bdstanley.netlify.app/jezyk-angielski-1-handout", "Wprowadzenie i podstawy biznesu") },
  { link("https://bdstanley.netlify.app/jezyk-angielski-2-handout", "Strategia i struktura") },
  { link("https://bdstanley.netlify.app/jezyk-angielski-3-handout", "Kultura organizacyjna i przywództwo") },
  { link("https://bdstanley.netlify.app/jezyk-angielski-4-handout", "Finanse, ludzie i innowacje") },
  { link("https://bdstanley.netlify.app/jezyk-angielski-5-handout", "Umiejętności pisania zawodowego") },
  { link("https://bdstanley.netlify.app/jezyk-angielski-6-handout", "Umiejętności komunikacji ustnej") },
)

#heading(level: 2)[#"Ćwiczenia"]

#list(
  { link("https://bdstanley.netlify.app/jezyk-angielski-1-exercises", "Wprowadzenie i podstawy biznesu") },
  { link("https://bdstanley.netlify.app/jezyk-angielski-2-exercises", "Strategia i struktura") },
  { link("https://bdstanley.netlify.app/jezyk-angielski-3-exercises", "Kultura organizacyjna i przywództwo") },
  { link("https://bdstanley.netlify.app/jezyk-angielski-4-exercises", "Finanse, ludzie i innowacje") },
  { link("https://bdstanley.netlify.app/jezyk-angielski-5-exercises", "Umiejętności pisania zawodowego") + [#" · "] + link("https://bdstanley.netlify.app/jezyk-angielski-5-exercises-answers", "answers") },
  { link("https://bdstanley.netlify.app/jezyk-angielski-6-exercises", "Umiejętności komunikacji ustnej") + [#" · "] + link("https://bdstanley.netlify.app/jezyk-angielski-6-exercises-answers", "answers") },
)

#heading(level: 2)[#"Zaliczenie"]

#list(
  { link("https://bdstanley.netlify.app/jezyk-angielski-oral-exam-instructions", "Sprawdzian ustny: pytania otwarte") },
)
