// AUTO-GENERATED by scripts/sync-teaching.py from the Teaching repo.
// Do not edit by hand — re-run build.sh (or the script) to regenerate.

#set document(title: "Podstawy dziennikarstwa danych")
#metadata((title: "Podstawy dziennikarstwa danych")) <website-metadata>

#html.elem("p", attrs: (class: "teaching-back"))[#link("../teaching.html", "← All courses")]

#heading(level: 1)[#"Podstawy dziennikarstwa danych"]

#heading(level: 2)[#"Slajdy"]

#enum(
  { link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-1-slides", "Wprowadzenie do dziennikarstwa danych") },
  { link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-2-slides", "Źródła i pozyskiwanie danych") },
  { link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-3-slides", "Narzędzia i analiza danych") },
  { link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-4-slides", "Wizualizacja danych") },
  { link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-5-slides", "Budowanie narracji — od danych do historii") },
)

#heading(level: 2)[#"Materiały"]

#list(
  { link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-1-handout", "Wprowadzenie do dziennikarstwa danych") },
  { link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-2-handout", "Źródła i pozyskiwanie danych") },
  { link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-3-handout", "Narzędzia i analiza danych") },
  { link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-3-handout-datawrapper", "Datawrapper — poradnik do ćwiczenia") },
  { link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-3-handout-jamovi", "jamovi — poradnik do ćwiczenia") },
  { link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-4-handout", "Wizualizacja danych") },
)

#heading(level: 2)[#"Ćwiczenia"]

#list(
  { link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-1-exercise", "Identyfikacja tematów wymagających dziennikarstwa danych") },
  { link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-2-exercise", "Źródła i pozyskiwanie danych") },
  { link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-3-exercise", "Narzędzia i analiza danych") + [#" · "] + link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-3-exercise-answers", "answers") },
  { link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-4-exercise", "Wizualizacja danych waszego projektu") },
  { link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-5-exercise-group-0", "Ćwiczenie narracyjne — Przykład (UK Housing)") + [#" · "] + link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-5-exercise-group-0-plan", "plan modelowy") + [#" · "] + link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-5-exercise-group-0-projekt", "artykuł") + [#" · "] + link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-5-exercise-group-0-dokumentacja", "dokumentacja") },
  { link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-5-exercise-group-1", "Ćwiczenie narracyjne — Grupa 1") + [#" · "] + link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-5-exercise-group-1-plan", "plan modelowy") + [#" · "] + link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-5-exercise-group-1-projekt", "artykuł") + [#" · "] + link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-5-exercise-group-1-dokumentacja", "dokumentacja") },
  { link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-5-exercise-group-2", "Ćwiczenie narracyjne — Grupa 2") + [#" · "] + link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-5-exercise-group-2-plan", "plan modelowy") + [#" · "] + link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-5-exercise-group-2-projekt", "artykuł") + [#" · "] + link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-5-exercise-group-2-dokumentacja", "dokumentacja") },
  { link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-5-exercise-group-3", "Ćwiczenie narracyjne — Grupa 3") + [#" · "] + link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-5-exercise-group-3-plan", "plan modelowy") + [#" · "] + link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-5-exercise-group-3-projekt", "artykuł") + [#" · "] + link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-5-exercise-group-3-dokumentacja", "dokumentacja") },
  { link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-5-exercise-group-4", "Ćwiczenie narracyjne — Grupa 4") + [#" · "] + link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-5-exercise-group-4-plan", "plan modelowy") + [#" · "] + link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-5-exercise-group-4-projekt", "artykuł") + [#" · "] + link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-5-exercise-group-4-dokumentacja", "dokumentacja") },
  { link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-5-exercise-group-5", "Ćwiczenie narracyjne — Grupa 5") + [#" · "] + link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-5-exercise-group-5-plan", "plan modelowy") + [#" · "] + link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-5-exercise-group-5-projekt", "artykuł") + [#" · "] + link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-5-exercise-group-5-dokumentacja", "dokumentacja") },
  { link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-5-exercise-group-6", "Ćwiczenie narracyjne — Grupa 6") + [#" · "] + link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-5-exercise-group-6-plan", "plan modelowy") + [#" · "] + link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-5-exercise-group-6-projekt", "artykuł") + [#" · "] + link("https://bdstanley.netlify.app/podstawy-dziennikarstwa-5-exercise-group-6-dokumentacja", "dokumentacja") },
)

#heading(level: 2)[#"Źródła"]

#heading(level: 3)[#"Dane do ćwiczeń"]

#list(
  { link("https://bdstanley.netlify.app/Podstawy%20dziennikarstwa%20danych/Resources/przestepstwa-powiaty-2025.csv", "przestepstwa-powiaty-2025.csv") },
  { link("https://bdstanley.netlify.app/Podstawy%20dziennikarstwa%20danych/Resources/wydatki_miasta_2024.csv", "wydatki_miasta_2024.csv") },
)
