// AUTO-GENERATED by scripts/sync-teaching.py from the Teaching repo.
// Do not edit by hand — re-run build.sh (or the script) to regenerate.

#set document(title: "The Social Psychology of Democracies in Transition")
#metadata((title: "The Social Psychology of Democracies in Transition")) <website-metadata>

#html.elem("p", attrs: (class: "teaching-back"))[#link("../teaching.html", "← All courses")]

#heading(level: 1)[#"The Social Psychology of Democracies in Transition"]

#heading(level: 2)[#"Slides"]

#enum(
  { link("https://bdstanley.netlify.app/social-psychology-democracies-1-slides", "Introduction") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-2-slides", "Transition to (and from?) democracy: an overview") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-3-slides", "Legacies of communism") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-4-slides", "Social-psychological theories and communist legacies") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-5-slides", "The self under communism and the self after communism") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-6-slides", "Attitudes, values, orientations and beliefs") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-7-slides", "Social influence and social norms") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-8-slides", "Anti-social behaviour: anomie and aggression") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-9-slides", "Pro-social behaviour: helping and altruism") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-10-slides", "Groups and group dynamics") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-11-slides", "Prejudice and intergroup relations (1): the nature of post-communist prejudice") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-12-slides", "Prejudice and intergroup relations (2): reducing prejudice") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-13-slides", "Cultural social psychology: intercultural relations") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-14-slides", "The psychological underpinnings of democracy and democratic backsliding") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-15-slides", "Course synthesis and exam preparation") },
)

#heading(level: 2)[#"Handouts"]

#list(
  { link("https://bdstanley.netlify.app/social-psychology-democracies-1-handout", "Introduction") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-2-handout", "Transition to (and from?) democracy: an overview") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-3-handout", "Legacies of communism") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-4-handout", "Social-psychological theories and communist legacies") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-5-handout", "The self under communism and the self after communism") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-6-handout", "Attitudes, values, orientations and beliefs") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-7-handout", "Social influence and social norms") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-8-handout", "Anti-social behaviour: anomie and aggression") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-9-handout", "Pro-social behaviour: helping and altruism") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-10-handout", "Groups and group dynamics") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-11-handout", "Prejudice and intergroup relations (1): the nature of post-communist prejudice") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-12-handout", "Prejudice and intergroup relations (2): reducing prejudice") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-13-handout", "Cultural social psychology: intercultural relations") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-14-handout", "The psychological underpinnings of democracy and democratic backsliding") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-15-handout", "Course synthesis and exam preparation") },
)
