// AUTO-GENERATED by scripts/sync-teaching.py from the Teaching repo.
// Do not edit by hand — re-run build.sh (or the script) to regenerate.

#set document(title: "Introduction to Social Research Methodology")
#metadata((title: "Introduction to Social Research Methodology")) <website-metadata>

#html.elem("p", attrs: (class: "teaching-back"))[#link("../teaching.html", "← All courses")]

#heading(level: 1)[#"Introduction to Social Research Methodology"]

#heading(level: 2)[#"Slides"]

#enum(
  { link("https://bdstanley.netlify.app/social-research-methodology-1-slides", "The nature and purpose of social research") },
)

#heading(level: 2)[#"Handouts"]

#list(
  { link("https://bdstanley.netlify.app/social-research-methodology-1-handout", "The nature and purpose of social research") },
)
