// AUTO-GENERATED by scripts/sync-teaching.py from the Teaching repo.
// Do not edit by hand — re-run build.sh (or the script) to regenerate.

#set document(title: "The Social Psychology of Democracies in Transition")
#metadata((title: "The Social Psychology of Democracies in Transition")) <website-metadata>

#html.elem("p", attrs: (class: "teaching-back"))[#link("../teaching.html", "← All courses")]

#heading(level: 1)[#"The Social Psychology of Democracies in Transition"]

#heading(level: 2)[#"Slides"]

#enum(
  { link("https://bdstanley.netlify.app/social-psychology-democracies-1-slides", "social psychology democracies 1 slides") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-2-slides", "social psychology democracies 2 slides") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-3-slides", "social psychology democracies 3 slides") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-4-slides", "social psychology democracies 4 slides") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-5-slides", "social psychology democracies 5 slides") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-6-slides", "social psychology democracies 6 slides") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-7-slides", "social psychology democracies 7 slides") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-8-slides", "social psychology democracies 8 slides") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-9-slides", "social psychology democracies 9 slides") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-10-slides", "social psychology democracies 10 slides") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-11-slides", "social psychology democracies 11 slides") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-12-slides", "social psychology democracies 12 slides") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-13-slides", "social psychology democracies 13 slides") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-14-slides", "social psychology democracies 14 slides") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-15-slides", "social psychology democracies 15 slides") },
)

#heading(level: 2)[#"Handouts"]

#list(
  { link("https://bdstanley.netlify.app/social-psychology-democracies-1-handout", "social psychology democracies 1 handout") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-2-handout", "social psychology democracies 2 handout") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-3-handout", "social psychology democracies 3 handout") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-4-handout", "social psychology democracies 4 handout") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-5-handout", "social psychology democracies 5 handout") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-6-handout", "social psychology democracies 6 handout") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-7-handout", "social psychology democracies 7 handout") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-8-handout", "social psychology democracies 8 handout") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-9-handout", "social psychology democracies 9 handout") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-10-handout", "social psychology democracies 10 handout") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-11-handout", "social psychology democracies 11 handout") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-12-handout", "social psychology democracies 12 handout") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-13-handout", "social psychology democracies 13 handout") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-14-handout", "social psychology democracies 14 handout") },
  { link("https://bdstanley.netlify.app/social-psychology-democracies-15-handout", "social psychology democracies 15 handout") },
)
