// AUTO-GENERATED by scripts/sync-teaching.py from the Teaching repo.
// Do not edit by hand — re-run build.sh (or the script) to regenerate.

#set document(title: "Systemy polityczne")
#metadata((title: "Systemy polityczne")) <website-metadata>

#html.elem("p", attrs: (class: "teaching-back"))[#link("../teaching.html", "← All courses")]

#heading(level: 1)[#"Systemy polityczne"]

#heading(level: 2)[#"Slajdy"]

#enum(
  { link("https://bdstanley.netlify.app/systemy-polityczne-1-slides", "Systemy polityczne - pojęcia i typy") },
  { link("https://bdstanley.netlify.app/systemy-polityczne-2-slides", "Demokratyczne systemy polityczne") },
  { link("https://bdstanley.netlify.app/systemy-polityczne-3-slides", "Niedemokratyczne systemy polityczne") },
  { link("https://bdstanley.netlify.app/systemy-polityczne-4-slides", "Konstytucja i system polityczny w Polsce. Wartość praworządności.") },
  { link("https://bdstanley.netlify.app/systemy-polityczne-5-slides", "Państwo prawa. Instytucje, procedury, ochrona praw i wolności. Rola mediów.") },
  { link("https://bdstanley.netlify.app/systemy-polityczne-6-slides", "Pięć kryzysów demokracji w XXI wieku") },
)

#heading(level: 2)[#"Materiały"]

#list(
  { link("https://bdstanley.netlify.app/systemy-polityczne-1-handout", "Systemy polityczne — pojęcia i typy") },
  { link("https://bdstanley.netlify.app/systemy-polityczne-2-handout", "Demokratyczne systemy polityczne") },
  { link("https://bdstanley.netlify.app/systemy-polityczne-3-handout", "Niedemokratyczne systemy polityczne") },
  { link("https://bdstanley.netlify.app/systemy-polityczne-4-handout", "Konstytucja i system polityczny w Polsce. Wartość praworządności") },
  { link("https://bdstanley.netlify.app/systemy-polityczne-5-handout", "Państwo prawa: instytucje, procedury, ochrona praw i rola mediów") },
  { link("https://bdstanley.netlify.app/systemy-polityczne-6-handout", "Pięć kryzysów demokracji w XXI wieku") },
)

#heading(level: 2)[#"Ćwiczenia"]

#list(
  { link("https://bdstanley.netlify.app/systemy-polityczne-1-exercise", "Ćwiczenie: Klasyfikacja i porównanie systemów politycznych") + [#" · "] + link("https://bdstanley.netlify.app/systemy-polityczne-1-exercise-answers", "answers") },
  { link("https://bdstanley.netlify.app/systemy-polityczne-2-exercise", "Ćwiczenie: Zaprojektuj własną demokrację") + [#" · "] + link("https://bdstanley.netlify.app/systemy-polityczne-2-exercise-answers", "answers") },
  { link("https://bdstanley.netlify.app/systemy-polityczne-3-exercise", "Ćwiczenie: Projektowanie systemu w okresie transformacji") + [#" · "] + link("https://bdstanley.netlify.app/systemy-polityczne-3-exercise-answers", "answers") },
  { link("https://bdstanley.netlify.app/systemy-polityczne-4-exercise", "Ćwiczenie: Przeprojektowanie Konstytucji RP") + [#" · "] + link("https://bdstanley.netlify.app/systemy-polityczne-4-exercise-answers", "answers") },
  { link("https://bdstanley.netlify.app/systemy-polityczne-5-exercise", "Ćwiczenie: Audyt praworządności i plan naprawczy") + [#" · "] + link("https://bdstanley.netlify.app/systemy-polityczne-5-exercise-answers", "answers") },
  { link("https://bdstanley.netlify.app/systemy-polityczne-6-exercise", "Ćwiczenie: Pakiet odporności demokratycznej") + [#" · "] + link("https://bdstanley.netlify.app/systemy-polityczne-6-exercise-answers", "answers") },
)
