// AUTO-GENERATED by scripts/sync-teaching.py from the Teaching repo.
// Do not edit by hand — re-run build.sh (or the script) to regenerate.

#set document(title: "Unia Europejska i jej instytucje")
#metadata((title: "Unia Europejska i jej instytucje")) <website-metadata>

#html.elem("p", attrs: (class: "teaching-back"))[#link("../teaching.html", "← All courses")]

#heading(level: 1)[#"Unia Europejska i jej instytucje"]

#heading(level: 2)[#"Slajdy"]

#enum(
  { link("https://bdstanley.netlify.app/unia-europejska-1-slides", "Wprowadzenie do przedmiotu - UE w skrócie") },
  { link("https://bdstanley.netlify.app/unia-europejska-2-slides", "Rozszerzenie Unii Europejskiej") },
  { link("https://bdstanley.netlify.app/unia-europejska-3-slides", "Pogłębienie integracji europejskiej") },
  { link("https://bdstanley.netlify.app/unia-europejska-4-slides", "Zasady działania Unii Europejskiej") },
  { link("https://bdstanley.netlify.app/unia-europejska-5-slides", "Komisja Europejska - struktura i kompetencje") },
  { link("https://bdstanley.netlify.app/unia-europejska-6-slides", "Rada Unii Europejskiej - struktura i kompetencje") },
  { link("https://bdstanley.netlify.app/unia-europejska-7-slides", "Rada Europejska - struktura i kompetencje") },
  { link("https://bdstanley.netlify.app/unia-europejska-8-slides", "Parlament Europejski - struktura i kompetencje") },
  { link("https://bdstanley.netlify.app/unia-europejska-9-slides", "System sądowy Unii Europejskiej") },
  { link("https://bdstanley.netlify.app/unia-europejska-10-slides", "Pozostałe instytucje UE") },
  { link("https://bdstanley.netlify.app/unia-europejska-11-slides", "Rola państw członkowskich w UE") },
  { link("https://bdstanley.netlify.app/unia-europejska-12-slides", "Procesy polityczne w Unii Europejskiej") },
  { link("https://bdstanley.netlify.app/unia-europejska-13-slides", "Polityka wewnętrzna UE") },
  { link("https://bdstanley.netlify.app/unia-europejska-14-slides", "Polityka zewnętrzna UE") },
  { link("https://bdstanley.netlify.app/unia-europejska-15-slides", "UE jako system polityczny - podsumowanie") },
)

#heading(level: 2)[#"Materiały"]

#list(
  { link("https://bdstanley.netlify.app/unia-europejska-1-handout", "Wprowadzenie do przedmiotu - UE w skrócie") },
  { link("https://bdstanley.netlify.app/unia-europejska-2-handout", "Rozszerzenie Unii Europejskiej") },
  { link("https://bdstanley.netlify.app/unia-europejska-3-handout", "Pogłębienie integracji europejskiej") },
  { link("https://bdstanley.netlify.app/unia-europejska-4-handout", "Zasady działania Unii Europejskiej") },
  { link("https://bdstanley.netlify.app/unia-europejska-5-handout", "Komisja Europejska - struktura i kompetencje") },
  { link("https://bdstanley.netlify.app/unia-europejska-6-handout", "Rada Unii Europejskiej - struktura i kompetencje") },
  { link("https://bdstanley.netlify.app/unia-europejska-7-handout", "Rada Europejska — struktura i kompetencje") },
  { link("https://bdstanley.netlify.app/unia-europejska-8-handout", "Parlament Europejski — struktura i kompetencje") },
  { link("https://bdstanley.netlify.app/unia-europejska-9-handout", "System sądowy Unii Europejskiej") },
  { link("https://bdstanley.netlify.app/unia-europejska-10-handout", "Pozostałe instytucje i organy UE") },
  { link("https://bdstanley.netlify.app/unia-europejska-11-handout", "Rola państw członkowskich w systemie UE") },
  { link("https://bdstanley.netlify.app/unia-europejska-12-handout", "Procesy polityczne w Unii Europejskiej") },
  { link("https://bdstanley.netlify.app/unia-europejska-13-handout", "Polityka wewnętrzna Unii Europejskiej") },
  { link("https://bdstanley.netlify.app/unia-europejska-14-handout", "Polityka zewnętrzna Unii Europejskiej") },
  { link("https://bdstanley.netlify.app/unia-europejska-15-handout", "UE jako system polityczny — podsumowanie") },
)
