// AUTO-GENERATED by scripts/sync-teaching.py from the Teaching repo.
// Do not edit by hand — re-run build.sh (or the script) to regenerate.

#set document(title: "Wprowadzenie do metodologii badań społecznych")
#metadata((title: "Wprowadzenie do metodologii badań społecznych")) <website-metadata>

#html.elem("p", attrs: (class: "teaching-back"))[#link("../teaching.html", "← All courses")]

#heading(level: 1)[#"Wprowadzenie do metodologii badań społecznych"]

#heading(level: 2)[#"Slajdy"]

#enum(
  { link("https://bdstanley.netlify.app/wprowadzenie-metodologia-1-slides", "Wprowadzenie do projektowania procesu badawczego") },
  { link("https://bdstanley.netlify.app/wprowadzenie-metodologia-2-slides", "Przegląd literatury. Analiza danych zastanych. Plagiat. Stosowanie referencji.") },
  { link("https://bdstanley.netlify.app/wprowadzenie-metodologia-3-slides", "Ujęcia jakościowe, ilościowe, mieszane") },
  { link("https://bdstanley.netlify.app/wprowadzenie-metodologia-4-slides", "Planowanie, organizacja i realizacja projektu badawczego") },
  { link("https://bdstanley.netlify.app/wprowadzenie-metodologia-5-slides", "Etyka w badaniach społecznych") },
  { link("https://bdstanley.netlify.app/wprowadzenie-metodologia-6-slides", "Logika doboru próby") },
  { link("https://bdstanley.netlify.app/wprowadzenie-metodologia-7-slides", "Badania ilościowe") },
  { link("https://bdstanley.netlify.app/wprowadzenie-metodologia-8-slides", "Badania jakościowe") },
  { link("https://bdstanley.netlify.app/wprowadzenie-metodologia-9-slides", "Analiza danych ilościowych") },
  { link("https://bdstanley.netlify.app/wprowadzenie-metodologia-10-slides", "Analiza danych jakościowych") },
  { link("https://bdstanley.netlify.app/wprowadzenie-metodologia-11-slides", "Opis i prezentowanie wyników badań") },
  { link("https://bdstanley.netlify.app/wprowadzenie-metodologia-12-slides", "Seminarium powtórzeniowe") },
)
