// AUTO-GENERATED by scripts/sync-teaching.py from the Teaching repo.
// Do not edit by hand — re-run build.sh (or the script) to regenerate.

#set document(title: "Wprowadzenie do metodologii badań społecznych")
#metadata((title: "Wprowadzenie do metodologii badań społecznych")) <website-metadata>

#html.elem("p", attrs: (class: "teaching-back"))[#link("../teaching.html", "← All courses")]

#heading(level: 1)[#"Wprowadzenie do metodologii badań społecznych"]

#heading(level: 2)[#"Slajdy"]

#enum(
  { link("https://bdstanley.netlify.app/wprowadzenie-metodologia-1-slides", "Wprowadzenie do projektowania procesu badawczego") },
  { link("https://bdstanley.netlify.app/wprowadzenie-metodologia-2-slides", "Przegląd literatury. Analiza danych zastanych. Plagiat. Stosowanie referencji.") },
  { link("https://bdstanley.netlify.app/wprowadzenie-metodologia-3-slides", "Ujęcia jakościowe, ilościowe, mieszane") },
  { link("https://bdstanley.netlify.app/wprowadzenie-metodologia-4-slides", "Planowanie, organizacja i realizacja projektu badawczego") },
  { link("https://bdstanley.netlify.app/wprowadzenie-metodologia-5-slides", "Etyka w badaniach społecznych") },
  { link("https://bdstanley.netlify.app/wprowadzenie-metodologia-6-slides", "Logika doboru próby") },
  { link("https://bdstanley.netlify.app/wprowadzenie-metodologia-7-slides", "Badania ilościowe") },
  { link("https://bdstanley.netlify.app/wprowadzenie-metodologia-8-slides", "Badania jakościowe") },
  { link("https://bdstanley.netlify.app/wprowadzenie-metodologia-9-slides", "Analiza danych ilościowych") },
  { link("https://bdstanley.netlify.app/wprowadzenie-metodologia-10-slides", "Analiza danych jakościowych") },
  { link("https://bdstanley.netlify.app/wprowadzenie-metodologia-11-slides", "Opis i prezentowanie wyników badań") },
  { link("https://bdstanley.netlify.app/wprowadzenie-metodologia-12-slides", "Seminarium powtórzeniowe") },
)

#heading(level: 2)[#"Ćwiczenia"]

#list(
  { link("https://bdstanley.netlify.app/wprowadzenie-metodologia-2-exercise", "Ćwiczenie: Formułowanie pytania badawczego przy użyciu modelu PICO") + [#" · "] + link("https://bdstanley.netlify.app/wprowadzenie-metodologia-2-exercise-answers", "answers") },
  { link("https://bdstanley.netlify.app/wprowadzenie-metodologia-3-exercise", "Ćwiczenie: Dobór odpowiedniej metody badawczej") + [#" · "] + link("https://bdstanley.netlify.app/wprowadzenie-metodologia-3-exercise-answers", "answers") },
  { link("https://bdstanley.netlify.app/wprowadzenie-metodologia-4-exercise", "Ćwiczenie: Planowanie projektu badawczego") },
  { link("https://bdstanley.netlify.app/wprowadzenie-metodologia-5-exercise", "Ćwiczenie: Analiza dylematów etycznych w badaniach społecznych") + [#" · "] + link("https://bdstanley.netlify.app/wprowadzenie-metodologia-5-exercise-answers", "answers") },
  { link("https://bdstanley.netlify.app/wprowadzenie-metodologia-6-exercise", "Ćwiczenie: Projektowanie doboru próby") },
  { link("https://bdstanley.netlify.app/wprowadzenie-metodologia-7-exercise-1", "Ćwiczenie 1: Korekta kwestionariusza badawczego") + [#" · "] + link("https://bdstanley.netlify.app/wprowadzenie-metodologia-7-exercise-1-answers", "answers") },
  { link("https://bdstanley.netlify.app/wprowadzenie-metodologia-7-exercise-2", "Ćwiczenie 2: Projektowanie pytań kwestionariuszowych") },
  { link("https://bdstanley.netlify.app/wprowadzenie-metodologia-7-exercise-2-notes", "Notatki do prezentacji: Projektowanie pytań kwestionariuszowych") },
  { link("https://bdstanley.netlify.app/wprowadzenie-metodologia-8-exercise", "Badania jakościowe - projektowanie scenariusza wywiadu") },
  { link("https://bdstanley.netlify.app/wprowadzenie-metodologia-10-exercise", "Analiza danych jakościowych - kodowanie i kategoryzacja") + [#" · "] + link("https://bdstanley.netlify.app/wprowadzenie-metodologia-10-exercise-answers", "answers") },
  { link("https://bdstanley.netlify.app/wprowadzenie-metodologia-11-exercise-1-part-1", "Wpływ korzystania z mediów społecznościowych na samoocenę nastolatków") },
  { link("https://bdstanley.netlify.app/wprowadzenie-metodologia-11-exercise-1-part-2", "Ćwiczenie: Identyfikacja błędów formatowania") },
)
