// AUTO-GENERATED by scripts/sync-teaching.py from the Teaching repo.
// Do not edit by hand — re-run build.sh (or the script) to regenerate.

#set document(title: "Teaching")
#metadata((title: "Teaching")) <website-metadata>

#heading(level: 1)[#"2026 summer term"]
#html.elem("div", attrs: (class: "course-grid"))[
#html.elem("a", attrs: (class: "course-card", href: "teaching/unia-europejska.html"))[#"Unia Europejska i jej instytucje"]
#html.elem("a", attrs: (class: "course-card", href: "teaching/jezyk-angielski.html"))[#"Język angielski w zastosowaniu zawodowym"]
#html.elem("a", attrs: (class: "course-card", href: "teaching/podstawy-dziennikarstwa.html"))[#"Podstawy dziennikarstwa danych"]
#html.elem("a", attrs: (class: "course-card", href: "teaching/social-psychology-democracies.html"))[#"Social Psychology of Democracies in Transition"]
]

#heading(level: 1)[#"2025 winter term"]
#html.elem("div", attrs: (class: "course-grid"))[
#html.elem("a", attrs: (class: "course-card", href: "teaching/wprowadzenie-metodologia.html"))[#"Wprowadzenie do metodologii badań społecznych"]
#html.elem("a", attrs: (class: "course-card", href: "teaching/dziennikarstwo-danych.html"))[#"Dziennikarstwo danych"]
#html.elem("a", attrs: (class: "course-card", href: "teaching/wyzwania-uprzedzenia.html"))[#"Wyzwania życia publicznego - uprzedzenia"]
#html.elem("a", attrs: (class: "course-card", href: "teaching/systemy-polityczne.html"))[#"Systemy polityczne"]
]
