#!/usr/bin/env python3
"""Generate the benstanley.eu Teaching pages from the Teaching repo.

READ-ONLY with respect to the Teaching repo (BDStanley/Classes). It parses the
Quarto sources there and writes Typst pages into THIS site:

    pages/teaching.typ              the landing page (Heiss-style course cards)
    pages/teaching/<slug>.typ       one page per course (slide/handout link lists)

The per-course pages list the same links/stubs as the Teaching repo's `.qmd`
files; each link points at the already-rendered artifact on the Netlify
teaching site (https://bdstanley.netlify.app/<stub>). Nothing is copied or
re-rendered — only the small index/course markdown is read.

build.sh runs this before `calepin compile`, so editing the Teaching repo and
rebuilding benstanley.eu reflects the changes here. The Teaching repo location
and the Netlify base URL can be overridden with env vars TEACHING_SRC and
TEACHING_NETLIFY_BASE.
"""

from __future__ import annotations

import os
import re
import shutil
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths / config
# ---------------------------------------------------------------------------
SCRIPT_DIR = Path(__file__).resolve().parent          # calepin-site/scripts
SITE_DIR = SCRIPT_DIR.parent                           # calepin-site
PAGES_DIR = SITE_DIR / "pages"
LANDING_FILE = PAGES_DIR / "teaching.typ"
COURSE_DIR = PAGES_DIR / "teaching"

# Default: the sibling Teaching checkout (…/Positron/Teaching).
DEFAULT_TEACHING_SRC = SITE_DIR.parent.parent / "Teaching"
TEACHING_SRC = Path(os.environ.get("TEACHING_SRC", str(DEFAULT_TEACHING_SRC)))
NETLIFY_BASE = os.environ.get("TEACHING_NETLIFY_BASE", "https://bdstanley.netlify.app").rstrip("/")

GENERATED_NOTE = (
    "// AUTO-GENERATED by scripts/sync-teaching.py from the Teaching repo.\n"
    "// Do not edit by hand — re-run build.sh (or the script) to regenerate.\n"
)

LINK_RE = re.compile(r"\[([^\]]*)\]\(([^)]+)\)")
H_RE = re.compile(r"^(#{2,6})\s+(.*)$")
OL_RE = re.compile(r"^\s*\d+\.\s+(.*)$")
UL_RE = re.compile(r"^\s*[-*]\s+(.*)$")
INDEX_TERM_RE = re.compile(r"^##\s+(.*)$")
INDEX_COURSE_RE = re.compile(r"^###\s+\[([^\]]+)\]\(([^)]+)\)\s*$")


# ---------------------------------------------------------------------------
# Text helpers
# ---------------------------------------------------------------------------
def smart(s: str) -> str:
    """Mimic Quarto/pandoc smart dashes so display text matches the rendered site."""
    return s.replace("---", "—").replace("--", "–")


def tystr(s: str) -> str:
    """Escape a (display) string for use inside a Typst string literal."""
    return smart(s).replace("\\", "\\\\").replace('"', '\\"')


def resolve_href(target: str) -> str:
    """Turn a Teaching-repo link target into an absolute URL on the Netlify site,
    keeping the original stub/path exactly as authored."""
    t = target.strip()
    if t.startswith("http://") or t.startswith("https://"):
        return t
    if t.startswith("/"):
        return NETLIFY_BASE + t
    return NETLIFY_BASE + "/" + t


def split_frontmatter(text: str) -> tuple[dict, str]:
    """Return (frontmatter dict (title only), body) for a .qmd file."""
    lines = text.splitlines()
    fm: dict[str, str] = {}
    body = lines
    if lines and lines[0].strip() == "---":
        for i in range(1, len(lines)):
            if lines[i].strip() == "---":
                for fl in lines[1:i]:
                    m = re.match(r"^title:\s*(.+)$", fl.strip())
                    if m:
                        fm["title"] = m.group(1).strip().strip('"').strip("'")
                body = lines[i + 1 :]
                break
    return fm, "\n".join(body)


# ---------------------------------------------------------------------------
# Parsing course bodies into blocks
# ---------------------------------------------------------------------------
def parse_item_parts(item: str):
    """Split a list item into ordered parts: ('link', label, href) | ('text', s)."""
    parts = []
    pos = 0
    for m in LINK_RE.finditer(item):
        if m.start() > pos:
            txt = item[pos : m.start()]
            if txt:
                parts.append(("text", txt))
        parts.append(("link", m.group(1), resolve_href(m.group(2))))
        pos = m.end()
    tail = item[pos:]
    if tail:
        parts.append(("text", tail))
    return parts


def parse_course_body(body: str):
    """Return an ordered list of blocks: heading / olist / ulist."""
    blocks = []
    cur_list = None  # ("ol"|"ul", [items])

    def flush():
        nonlocal cur_list
        if cur_list:
            blocks.append(("olist" if cur_list[0] == "ol" else "ulist", cur_list[1]))
            cur_list = None

    for raw in body.splitlines():
        line = raw.rstrip()
        hm = H_RE.match(line)
        if hm:
            flush()
            blocks.append(("heading", len(hm.group(1)), hm.group(2).strip()))
            continue
        om = OL_RE.match(line)
        if om:
            if not cur_list or cur_list[0] != "ol":
                flush()
                cur_list = ("ol", [])
            cur_list[1].append(parse_item_parts(om.group(1).strip()))
            continue
        um = UL_RE.match(line)
        if um:
            if not cur_list or cur_list[0] != "ul":
                flush()
                cur_list = ("ul", [])
            cur_list[1].append(parse_item_parts(um.group(1).strip()))
            continue
        # blank or other → break any open list
        if line.strip() == "":
            flush()
    flush()
    return blocks


# ---------------------------------------------------------------------------
# Emitting Typst
# ---------------------------------------------------------------------------
def emit_item(parts) -> str:
    """One list item as a Typst code block evaluating to content."""
    pieces = []
    for p in parts:
        if p[0] == "link":
            pieces.append('link("%s", "%s")' % (tystr(p[2]), tystr(p[1])))
        else:
            pieces.append('[#"%s"]' % tystr(p[1]))
    return "{ " + " + ".join(pieces) + " }"


def emit_list(kind: str, items) -> str:
    fn = "enum" if kind == "olist" else "list"
    body = ",\n  ".join(emit_item(it) for it in items)
    return "#%s(\n  %s,\n)" % (fn, body)


def emit_course_page(title: str, blocks) -> str:
    out = [GENERATED_NOTE]
    out.append('#set document(title: "%s")' % tystr(title))
    out.append('#metadata((title: "%s")) <website-metadata>' % tystr(title))
    out.append("")
    out.append(
        '#html.elem("p", attrs: (class: "teaching-back"))[#link("../teaching.html", "← All courses")]'
    )
    out.append("")
    out.append('#heading(level: 1)[#"%s"]' % tystr(title))
    out.append("")
    for b in blocks:
        if b[0] == "heading":
            level = max(2, b[1])  # course title is the only h1
            out.append('#heading(level: %d)[#"%s"]' % (level, tystr(b[2])))
        else:
            out.append(emit_list(b[0], b[1]))
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def emit_landing(terms) -> str:
    out = [GENERATED_NOTE]
    out.append('#set document(title: "Teaching")')
    out.append('#metadata((title: "Teaching")) <website-metadata>')
    out.append("")
    for term in terms:
        # level 1 -> <h2> (Calepin demotes content headings by one), matching the
        # section-header weight used on the other pages.
        out.append('#heading(level: 1)[#"%s"]' % tystr(term["name"]))
        out.append('#html.elem("div", attrs: (class: "course-grid"))[')
        for c in term["courses"]:
            href = "teaching/%s.html" % c["slug"]
            out.append(
                '#html.elem("a", attrs: (class: "course-card", href: "%s"))[#"%s"]'
                % (href, tystr(c["title"]))
            )
        out.append("]")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main() -> int:
    index = TEACHING_SRC / "index.qmd"
    if not index.is_file():
        print(
            "  [teaching] source not found at %s — skipping (existing pages kept)."
            % TEACHING_SRC,
            file=sys.stderr,
        )
        return 0

    # Parse the landing index: terms -> courses (title + slug), preserving order.
    terms = []
    cur = None
    for line in index.read_text(encoding="utf-8").splitlines():
        tm = INDEX_TERM_RE.match(line)
        if tm:
            cur = {"name": tm.group(1).strip(), "courses": []}
            terms.append(cur)
            continue
        cm = INDEX_COURSE_RE.match(line)
        if cm and cur is not None:
            slug = Path(cm.group(2).strip()).stem  # foo.qmd -> foo
            cur["courses"].append({"title": cm.group(1).strip(), "slug": slug})

    # Clean previously generated output so removed courses disappear.
    if COURSE_DIR.exists():
        shutil.rmtree(COURSE_DIR)
    COURSE_DIR.mkdir(parents=True, exist_ok=True)

    n_courses = 0
    for term in terms:
        kept = []
        for c in term["courses"]:
            qmd = TEACHING_SRC / (c["slug"] + ".qmd")
            if not qmd.is_file():
                print("  [teaching] missing course file %s — skipping card." % qmd.name,
                      file=sys.stderr)
                continue
            fm, body = split_frontmatter(qmd.read_text(encoding="utf-8"))
            title = fm.get("title", c["title"])
            blocks = parse_course_body(body)
            (COURSE_DIR / (c["slug"] + ".typ")).write_text(
                emit_course_page(title, blocks), encoding="utf-8"
            )
            kept.append(c)
            n_courses += 1
        term["courses"] = kept

    LANDING_FILE.write_text(emit_landing(terms), encoding="utf-8")
    print("  [teaching] generated landing + %d course pages (links -> %s)."
          % (n_courses, NETLIFY_BASE))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
