#!/usr/bin/env python3
"""Generate the benstanley.eu Teaching pages from the Teaching repo (Quarto).

This is the Quarto twin of the Calepin site's scripts/sync-teaching.py: same
parsing and metadata logic, but it writes Quarto `.qmd` instead of Typst `.typ`.

READ-ONLY with respect to the Teaching repo (BDStanley/Classes). It parses the
Quarto sources there and writes into THIS site:

    pages/teaching.qmd              the landing page (Heiss-style flat course list)
    pages/teaching/<slug>.qmd       one page per course (slide/handout link lists)

The per-course pages list the same links/stubs as the Teaching repo's `.qmd`
files; each link points at the already-rendered artifact on the Netlify teaching
site (https://bdstanley.netlify.app/<stub>). Nothing is copied or re-rendered —
only the small index/course markdown is read.

build.sh runs this before `quarto render`, so editing the Teaching repo and
rebuilding the site reflects the changes here. The Teaching repo location and the
Netlify base URL can be overridden with env vars TEACHING_SRC and
TEACHING_NETLIFY_BASE.
"""

from __future__ import annotations

import os
import re
import shutil
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths / config
# ---------------------------------------------------------------------------
SCRIPT_DIR = Path(__file__).resolve().parent          # quarto-site/scripts
SITE_DIR = SCRIPT_DIR.parent                           # quarto-site
PAGES_DIR = SITE_DIR / "pages"
LANDING_FILE = PAGES_DIR / "teaching.qmd"
COURSE_DIR = PAGES_DIR / "teaching"

# Default: the sibling Teaching checkout (…/Positron/Teaching).
DEFAULT_TEACHING_SRC = SITE_DIR.parent.parent / "Teaching"
TEACHING_SRC = Path(os.environ.get("TEACHING_SRC", str(DEFAULT_TEACHING_SRC)))
NETLIFY_BASE = os.environ.get("TEACHING_NETLIFY_BASE", "https://bdstanley.netlify.app").rstrip("/")

GENERATED_NOTE = (
    "<!-- AUTO-GENERATED by scripts/sync-teaching.py from the Teaching repo.\n"
    "     Do not edit by hand — re-run build.sh (or the script) to regenerate. -->\n"
)

# ---------------------------------------------------------------------------
# Short course descriptions for the landing cards, in the LANGUAGE OF THE COURSE.
# These don't exist in the Teaching repo, so they're authored here. Drafted from
# each course's lecture topics — EDIT FREELY (this is the place to refine them).
# A slug with no entry simply renders without a description.
# ---------------------------------------------------------------------------
COURSE_DESCRIPTIONS = {
    "social-research-methodology":
        "An introduction to social research methodology: the nature and purpose of social "
        "research, qualitative and quantitative approaches, and the stages of the research "
        "process from design to interpretation.",
    "english-professional-purposes":
        "English for the professional workplace: reading comprehension, grammar and business "
        "vocabulary, writing proposals, and delivering presentations.",
    "unia-europejska":
        "Funkcjonowanie instytucji Unii Europejskiej, proces integracji i rozszerzenia "
        "oraz rola państw członkowskich w systemie politycznym UE.",
    "jezyk-angielski":
        "Język angielski w kontekście zawodowym i biznesowym: komunikacja pisemna i ustna, "
        "kultura organizacyjna, przywództwo oraz słownictwo biznesowe.",
    "podstawy-dziennikarstwa":
        "Wprowadzenie do dziennikarstwa danych: pozyskiwanie i analiza danych, wizualizacja "
        "oraz budowanie narracji opartej na danych.",
    "social-psychology-democracies":
        "The social psychology of post-communist transition: communist legacies, attitudes "
        "and values, intergroup relations, and the foundations of democracy and democratic "
        "backsliding.",
    "wprowadzenie-metodologia":
        "Projektowanie badań społecznych: podejścia ilościowe, jakościowe i mieszane, dobór "
        "próby, etyka oraz analiza i prezentacja wyników.",
    "dziennikarstwo-danych":
        "Czym jest dziennikarstwo danych: źródła i analiza danych, narzędzia, wizualizacja "
        "oraz krytyczna ocena praktyki dziennikarskiej.",
    "wyzwania-uprzedzenia":
        "Stereotypy, uprzedzenia i dyskryminacja: mechanizmy powstawania uprzedzeń, "
        "tożsamość społeczna oraz społeczne konsekwencje uprzedzeń.",
    "systemy-polityczne":
        "Pojęcia i typy systemów politycznych, systemy demokratyczne i niedemokratyczne, "
        "konstytucja i praworządność w Polsce oraz współczesne kryzysy demokracji.",
}

# Course codes for courses whose slide decks carry no code in their footer. Taken
# from the SWPS course catalogue (USOS). Fallback only — a code found in the
# slides always wins. Edit/extend as the catalogue changes.
COURSE_CODES = {
    "dziennikarstwo-danych": "DZ.N22.T10",
    "systemy-polityczne": "DZ.S13.T18",
    "wprowadzenie-metodologia": "ZA.S11.T40",
    "wyzwania-uprzedzenia": "ZP.S12.T13",
}

# Season → (within-calendar-year rank, English label, Polish label). The badge
# for each term is shown in the LANGUAGE OF THE COURSE (English vs Polish). Badges
# are sorted by (calendar year, rank); within a calendar year the spring/summer
# semester (starts ~Feb) precedes the autumn/winter semester (starts ~Oct).
SEASONS = {
    "spring": (0, "Spring", "Wiosna"),
    "summer": (0, "Summer", "Lato"),
    "letni":  (0, "Summer", "Lato"),
    "fall":   (1, "Fall", "Jesień"),
    "autumn": (1, "Autumn", "Jesień"),
    "winter": (1, "Winter", "Zima"),
    "zimowy": (1, "Winter", "Zima"),
}

LINK_RE = re.compile(r"\[([^\]]*)\]\(([^)]+)\)")
H_RE = re.compile(r"^(#{2,6})\s+(.*)$")
OL_RE = re.compile(r"^\s*\d+\.\s+(.*)$")
UL_RE = re.compile(r"^\s*[-*]\s+(.*)$")
INDEX_TERM_RE = re.compile(r"^##\s+(.*)$")
INDEX_COURSE_RE = re.compile(r"^###\s+\[([^\]]+)\]\(([^)]+)\)\s*$")


# ---------------------------------------------------------------------------
# Text helpers
# ---------------------------------------------------------------------------
def smart(s: str) -> str:
    """Mimic Quarto/pandoc smart dashes so display text matches the rendered site."""
    return s.replace("---", "—").replace("--", "–")


def html_escape(s: str) -> str:
    """Escape a (display) string for use inside the landing's raw HTML."""
    return (smart(s)
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;"))


def yaml_str(s: str) -> str:
    """Escape a string for use as a double-quoted YAML scalar (front matter title)."""
    return smart(s).replace("\\", "\\\\").replace('"', '\\"')


def md_label(s: str) -> str:
    """Escape a Markdown link label so brackets/backslashes don't break the link."""
    return (smart(s)
            .replace("\\", "\\\\")
            .replace("[", "\\[")
            .replace("]", "\\]"))


def resolve_href(target: str) -> str:
    """Turn a Teaching-repo link target into an absolute URL on the Netlify site,
    keeping the original stub/path exactly as authored."""
    t = target.strip()
    if t.startswith("http://") or t.startswith("https://"):
        return t
    if t.startswith("/"):
        return NETLIFY_BASE + t
    return NETLIFY_BASE + "/" + t


def split_frontmatter(text: str) -> tuple[dict, str]:
    """Return (frontmatter dict (title only), body) for a .qmd file."""
    lines = text.splitlines()
    fm: dict[str, str] = {}
    body = lines
    if lines and lines[0].strip() == "---":
        for i in range(1, len(lines)):
            if lines[i].strip() == "---":
                for fl in lines[1:i]:
                    m = re.match(r"^title:\s*(.+)$", fl.strip())
                    if m:
                        fm["title"] = m.group(1).strip().strip('"').strip("'")
                body = lines[i + 1 :]
                break
    return fm, "\n".join(body)


# ---------------------------------------------------------------------------
# Course metadata: academic year (from term), code/university/lang (from slides),
# and the hexsticker image source.
# ---------------------------------------------------------------------------
def parse_term(term_name: str):
    """'2026 summer term' -> {year, rank, en, pl}, or None if unparseable."""
    ym = re.search(r"(\d{4})", term_name)
    low = term_name.lower()
    season = next((s for s in SEASONS if s in low), None)
    if not ym or season is None:
        return None
    rank, en, pl = SEASONS[season]
    return {"year": int(ym.group(1)), "rank": rank, "en": en, "pl": pl}


def badge_label(term: dict, lang: str) -> str:
    """Term badge in the course's language, e.g. 'Winter 2025' / 'Zima 2026'."""
    if lang == "pl":
        word = term["pl"]
        return "%s %d" % (word[0].upper() + word[1:], term["year"])
    return "%s %d" % (term["en"], term["year"])


def slide_meta(slug: str) -> dict:
    """Pull code/university/lang from the course's first slide deck (.qmd)."""
    cands = sorted(TEACHING_SRC.glob("*/Slides/%s-1-slides.qmd" % slug))
    if not cands:
        cands = sorted(TEACHING_SRC.glob("*/Slides/%s-*-slides.qmd" % slug))
    out = {"code": None, "university": None, "lang": None}
    if not cands:
        return out
    text = cands[0].read_text(encoding="utf-8")
    lines = text.splitlines()
    fm = text
    if lines and lines[0].strip() == "---":
        for i in range(1, len(lines)):
            if lines[i].strip() == "---":
                fm = "\n".join(lines[1:i])
                break
    m = re.search(r'^\s*footer:\s*"(.*)"\s*$', fm, re.M)
    if m:
        cm = re.search(r"\(([^)]+)\)\s*$", m.group(1).strip())
        if cm:
            out["code"] = cm.group(1).strip()
    m = re.search(r"^\s*lang:\s*([A-Za-z-]+)\s*$", fm, re.M)
    if m:
        out["lang"] = m.group(1).strip()
    m = re.search(r'^\s*affiliation:\s*"(.*)"\s*$', fm, re.M)
    if m:
        aff = m.group(1).strip()
        out["university"] = aff.split(",")[-1].strip() if "," in aff else aff
    return out


def hex_src(slug: str) -> str:
    """Per-course hexsticker if one was dropped in assets/teaching/, else the
    shared placeholder. Paths are relative to the landing page (/pages/)."""
    assets = SITE_DIR / "assets" / "teaching"
    for ext in ("svg", "png", "jpg", "jpeg", "webp"):
        if (assets / ("%s.%s" % (slug, ext))).is_file():
            return "../assets/teaching/%s.%s" % (slug, ext)
    return "../assets/teaching/_placeholder.svg"


# ---------------------------------------------------------------------------
# Parsing course bodies into blocks
# ---------------------------------------------------------------------------
def parse_item_parts(item: str):
    """Split a list item into ordered parts: ('link', label, href) | ('text', s)."""
    parts = []
    pos = 0
    for m in LINK_RE.finditer(item):
        if m.start() > pos:
            txt = item[pos : m.start()]
            if txt:
                parts.append(("text", txt))
        parts.append(("link", m.group(1), resolve_href(m.group(2))))
        pos = m.end()
    tail = item[pos:]
    if tail:
        parts.append(("text", tail))
    return parts


def parse_course_body(body: str):
    """Return an ordered list of blocks: heading / olist / ulist."""
    blocks = []
    cur_list = None  # ("ol"|"ul", [items])

    def flush():
        nonlocal cur_list
        if cur_list:
            blocks.append(("olist" if cur_list[0] == "ol" else "ulist", cur_list[1]))
            cur_list = None

    for raw in body.splitlines():
        line = raw.rstrip()
        hm = H_RE.match(line)
        if hm:
            flush()
            blocks.append(("heading", len(hm.group(1)), hm.group(2).strip()))
            continue
        om = OL_RE.match(line)
        if om:
            if not cur_list or cur_list[0] != "ol":
                flush()
                cur_list = ("ol", [])
            cur_list[1].append(parse_item_parts(om.group(1).strip()))
            continue
        um = UL_RE.match(line)
        if um:
            if not cur_list or cur_list[0] != "ul":
                flush()
                cur_list = ("ul", [])
            cur_list[1].append(parse_item_parts(um.group(1).strip()))
            continue
        if line.strip() == "":
            flush()
    flush()
    return blocks


# ---------------------------------------------------------------------------
# Emitting Quarto markdown
# ---------------------------------------------------------------------------
def emit_item(parts) -> str:
    """One list item as inline Markdown (links + text concatenated)."""
    pieces = []
    for p in parts:
        if p[0] == "link":
            pieces.append("[%s](%s)" % (md_label(p[1]), p[2]))
        else:
            pieces.append(smart(p[1]))
    return "".join(pieces)


def emit_list(kind: str, items) -> str:
    lines = []
    for i, it in enumerate(items):
        prefix = ("%d." % (i + 1)) if kind == "olist" else "-"
        lines.append("%s %s" % (prefix, emit_item(it)))
    return "\n".join(lines)


def emit_course_page(title: str, blocks) -> str:
    out = ["---", 'title: "%s"' % yaml_str(title), "---", "", GENERATED_NOTE.rstrip(), ""]
    out.append('<p class="teaching-back"><a href="../teaching.html">← All courses</a></p>')
    out.append("")
    for b in blocks:
        if b[0] == "heading":
            level = max(2, b[1])  # the course title is the H1 (title block)
            out.append("%s %s" % ("#" * level, smart(b[2])))
        else:
            out.append(emit_list(b[0], b[1]))
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def emit_landing(entries) -> str:
    """Heiss-style landing: a single list of course rows (hexsticker · name ·
    description · one badge per semester taught), emitted as raw HTML."""
    out = ["---", 'title: "Teaching"', "---", "", GENERATED_NOTE.rstrip(), ""]
    out.append('<div class="course-list">')
    for e in entries:
        out.append('<div class="course-row">')
        out.append('<img class="course-hex" src="%s" alt="">' % e["hex"])
        out.append('<div class="course-body">')
        out.append('<a class="course-name" href="teaching/%s.html">%s</a>'
                   % (e["slug"], html_escape(e["title"])))
        if e["description"]:
            out.append('<div class="course-desc">%s</div>' % html_escape(e["description"]))
        if e["badges"]:
            out.append('<div class="course-terms">')
            for b in e["badges"]:
                out.append('<span class="course-term">%s</span>' % html_escape(b))
            out.append("</div>")
        out.append("</div>")  # course-body
        out.append("</div>")  # course-row
    out.append("</div>")  # course-list
    return "\n".join(out).rstrip() + "\n"


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main() -> int:
    index = TEACHING_SRC / "index.qmd"
    if not index.is_file():
        print(
            "  [teaching] source not found at %s — skipping (existing pages kept)."
            % TEACHING_SRC,
            file=sys.stderr,
        )
        return 0

    # Parse the landing index: terms -> courses (title + slug), preserving order.
    terms = []
    cur = None
    for line in index.read_text(encoding="utf-8").splitlines():
        tm = INDEX_TERM_RE.match(line)
        if tm:
            cur = {"name": tm.group(1).strip(), "courses": []}
            terms.append(cur)
            continue
        cm = INDEX_COURSE_RE.match(line)
        if cm and cur is not None:
            slug = Path(cm.group(2).strip()).stem  # foo.qmd -> foo
            cur["courses"].append({"title": cm.group(1).strip(), "slug": slug})

    # Clean previously generated output so removed courses disappear.
    if COURSE_DIR.exists():
        shutil.rmtree(COURSE_DIR)
    COURSE_DIR.mkdir(parents=True, exist_ok=True)

    # Generate per-course pages and collect a single flat list of courses (no
    # year grouping). A course is deduplicated by slug across all terms; each term
    # it appears in adds a badge.
    n_courses = 0
    by_slug: dict = {}
    order: list = []   # slug order = first appearance in index.qmd (page order)
    for term in terms:
        tinfo = parse_term(term["name"])
        for c in term["courses"]:
            slug = c["slug"]
            qmd = TEACHING_SRC / (slug + ".qmd")
            if not qmd.is_file():
                print("  [teaching] missing course file %s — skipping." % qmd.name, file=sys.stderr)
                continue

            if slug not in by_slug:
                fm, body = split_frontmatter(qmd.read_text(encoding="utf-8"))
                title = fm.get("title", c["title"])
                (COURSE_DIR / (slug + ".qmd")).write_text(
                    emit_course_page(title, parse_course_body(body)), encoding="utf-8"
                )
                n_courses += 1
                sm = slide_meta(slug)
                code = sm["code"] or COURSE_CODES.get(slug)   # slides win; else fallback
                univ = sm["university"]
                meta = ("%s | %s" % (code, univ)) if code and univ else (code or univ or "")
                hexsrc = hex_src(slug)
                missing = []
                if slug not in COURSE_DESCRIPTIONS:
                    missing.append("description")
                if hexsrc.endswith("_placeholder.svg"):
                    missing.append("icon")
                by_slug[slug] = {
                    "slug": slug,
                    "title": c["title"],      # the landing label curated in index.qmd
                    "meta": meta,
                    "description": COURSE_DESCRIPTIONS.get(slug, ""),
                    "hex": hexsrc,
                    "lang": sm["lang"],
                    "_badges": [],            # (year, rank, label) tuples
                    "_missing": missing,
                }
                order.append(slug)

            if tinfo is not None:
                e = by_slug[slug]
                e["_badges"].append((tinfo["year"], tinfo["rank"], badge_label(tinfo, e["lang"])))

    # Finalise each course's badges: chronological (oldest first), de-duplicated.
    entries = []
    for slug in order:
        e = by_slug[slug]
        seen, labels = set(), []
        for _, _, lbl in sorted(e["_badges"]):
            if lbl not in seen:
                seen.add(lbl)
                labels.append(lbl)
        e["badges"] = labels
        entries.append(e)

    LANDING_FILE.write_text(emit_landing(entries), encoding="utf-8")
    print("  [teaching] generated landing (%d courses) + %d course pages (links -> %s)."
          % (len(entries), n_courses, NETLIFY_BASE))

    flagged = [(e["slug"], e["_missing"]) for e in entries if e["_missing"]]
    if flagged:
        print("  [teaching] needs attention (run the add-teaching-course skill):")
        for slug, m in flagged:
            print("    - %s: missing %s" % (slug, ", ".join(m)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
